-- Effectifs définitifs de la Coupe du Monde 2026 — 48 équipes, 1246 joueurs.
--
-- Source : Wikipédia « 2026 FIFA World Cup squads »
--   (https://en.wikipedia.org/wiki/2026_FIFA_World_Cup_squads), via l'API MediaWiki
--   action=parse&prop=wikitext, récupéré le 2026-06-03 (après la deadline FIFA du 1er juin 2026,
--   listes officielles publiées le 2 juin). API-Football est exclu : le plan gratuit refuse la saison 2026.
--
-- Données parsées par joueur depuis le template {{nat fs g player|no=|pos=|name=|club=}} :
--   shirt_number = no= ; position = pos= ; name/display_name = texte affiché du lien wiki ; club = club=.
--   Postes normalisés vers la convention de la table (consommée par le combobox/typeahead) :
--   GK->GK, DF->DEF, MF->MID, FW->FWD.
--   name = display_name = nom complet verbatim de la source ; aucune valeur inventée (cellule vide -> NULL).
--   Toutes les valeurs sont présentes dans cette édition (0 numéro/poste/club manquant).
--
-- Mapping nom d'équipe Wikipédia -> ref.teams.fifa_code (variantes gérées) :
--   Czech Republic=CZE, Turkey=TUR, Bosnia and Herzegovina=BIH, South Korea=KOR, South Africa=RSA,
--   Ivory Coast=CIV, DR Congo=COD, United States=USA, Curaçao=CUW, Cape Verde=CPV, Saudi Arabia=KSA,
--   New Zealand=NZL. Les team_id sont résolus par fifa_code (indépendant des UUID local/prod).
--   10 équipes de ref.teams ne sont PAS à la CdM 2026 et ne reçoivent pas d'effectif :
--   BOL, CMR, CRC, DEN, ITA, JAM, NCL, NGA, POL, UAE.
--
-- Stratégie idempotente (re-exécutable sans doublon) :
--   1) UPSERT sur l'index unique (team_id, lower(name)) : insère les nouveaux, actualise
--      numéro/poste/club et réactive (active=true) les joueurs déjà présents.
--   2) DÉSACTIVE (active=false, PAS de DELETE) les joueurs des 48 équipes importées absents de la
--      liste définitive (préliminaires coupés ou variantes de nom remplacées). On préserve ainsi les
--      références FK ON DELETE SET NULL (ref.match_events.player_id, tournament_predictions.top_scorer_player_id).
--   Résultat : pour chaque équipe importée, l'effectif ACTIF = exactement la liste Wikipédia.

drop table if exists _wc_squads;
create temp table _wc_squads (
  fifa_code    text     not null,
  name         text     not null,
  display_name text     not null,
  position     text,
  shirt_number smallint,
  club         text
);

insert into _wc_squads (fifa_code, name, display_name, position, shirt_number, club) values
  ('ALG','Melvin Mastil','Melvin Mastil','GK',1,'Stade Nyonnais'),
  ('ALG','Aïssa Mandi','Aïssa Mandi','DEF',2,'Lille'),
  ('ALG','Achref Abada','Achref Abada','DEF',3,'USM Alger'),
  ('ALG','Mohamed Amine Tougai','Mohamed Amine Tougai','DEF',4,'Espérance de Tunis'),
  ('ALG','Zineddine Belaïd','Zineddine Belaïd','DEF',5,'JS Kabylie'),
  ('ALG','Ramiz Zerrouki','Ramiz Zerrouki','MID',6,'Twente'),
  ('ALG','Riyad Mahrez','Riyad Mahrez','FWD',7,'Al-Ahli'),
  ('ALG','Houssem Aouar','Houssem Aouar','MID',8,'Al-Ittihad'),
  ('ALG','Amine Gouiri','Amine Gouiri','FWD',9,'Marseille'),
  ('ALG','Farès Chaïbi','Farès Chaïbi','MID',10,'Eintracht Frankfurt'),
  ('ALG','Anis Hadj Moussa','Anis Hadj Moussa','FWD',11,'Feyenoord'),
  ('ALG','Nadhir Benbouali','Nadhir Benbouali','FWD',12,'Győri ETO'),
  ('ALG','Jaouen Hadjam','Jaouen Hadjam','DEF',13,'Young Boys'),
  ('ALG','Hicham Boudaoui','Hicham Boudaoui','MID',14,'Nice'),
  ('ALG','Rayan Aït-Nouri','Rayan Aït-Nouri','DEF',15,'Manchester City'),
  ('ALG','Oussama Benbot','Oussama Benbot','GK',16,'USM Alger'),
  ('ALG','Rafik Belghali','Rafik Belghali','DEF',17,'Hellas Verona'),
  ('ALG','Mohamed Amoura','Mohamed Amoura','FWD',18,'VfL Wolfsburg'),
  ('ALG','Nabil Bentaleb','Nabil Bentaleb','MID',19,'Lille'),
  ('ALG','Adil Boulbina','Adil Boulbina','FWD',20,'Al-Duhail'),
  ('ALG','Ramy Bensebaini','Ramy Bensebaini','DEF',21,'Borussia Dortmund'),
  ('ALG','Ibrahim Maza','Ibrahim Maza','MID',22,'Bayer Leverkusen'),
  ('ALG','Luca Zidane','Luca Zidane','GK',23,'Granada'),
  ('ALG','Yacine Titraoui','Yacine Titraoui','MID',24,'Charleroi'),
  ('ALG','Farès Ghedjemis','Farès Ghedjemis','FWD',25,'Frosinone'),
  ('ALG','Samir Chergui','Samir Chergui','DEF',26,'Paris FC'),
  ('ARG','Juan Musso','Juan Musso','GK',1,'Atlético Madrid'),
  ('ARG','Leonardo Balerdi','Leonardo Balerdi','DEF',2,'Marseille'),
  ('ARG','Nicolás Tagliafico','Nicolás Tagliafico','DEF',3,'Lyon'),
  ('ARG','Gonzalo Montiel','Gonzalo Montiel','DEF',4,'River Plate'),
  ('ARG','Leandro Paredes','Leandro Paredes','MID',5,'Boca Juniors'),
  ('ARG','Lisandro Martínez','Lisandro Martínez','DEF',6,'Manchester United'),
  ('ARG','Rodrigo De Paul','Rodrigo De Paul','MID',7,'Inter Miami CF'),
  ('ARG','Valentín Barco','Valentín Barco','MID',8,'Strasbourg'),
  ('ARG','Julián Alvarez','Julián Alvarez','FWD',9,'Atlético Madrid'),
  ('ARG','Lionel Messi','Lionel Messi','FWD',10,'Inter Miami CF'),
  ('ARG','Giovani Lo Celso','Giovani Lo Celso','MID',11,'Real Betis'),
  ('ARG','Gerónimo Rulli','Gerónimo Rulli','GK',12,'Marseille'),
  ('ARG','Cristian Romero','Cristian Romero','DEF',13,'Tottenham Hotspur'),
  ('ARG','Exequiel Palacios','Exequiel Palacios','MID',14,'Bayer Leverkusen'),
  ('ARG','Nicolás González','Nicolás González','MID',15,'Atlético Madrid'),
  ('ARG','Thiago Almada','Thiago Almada','FWD',16,'Atlético Madrid'),
  ('ARG','Giuliano Simeone','Giuliano Simeone','FWD',17,'Atlético Madrid'),
  ('ARG','Nico Paz','Nico Paz','FWD',18,'Como'),
  ('ARG','Nicolás Otamendi','Nicolás Otamendi','DEF',19,'Benfica'),
  ('ARG','Alexis Mac Allister','Alexis Mac Allister','MID',20,'Liverpool'),
  ('ARG','José Manuel López','José Manuel López','FWD',21,'Palmeiras'),
  ('ARG','Lautaro Martínez','Lautaro Martínez','FWD',22,'Inter Milan'),
  ('ARG','Emiliano Martínez','Emiliano Martínez','GK',23,'Aston Villa'),
  ('ARG','Enzo Fernández','Enzo Fernández','MID',24,'Chelsea'),
  ('ARG','Facundo Medina','Facundo Medina','DEF',25,'Marseille'),
  ('ARG','Nahuel Molina','Nahuel Molina','DEF',26,'Atlético Madrid'),
  ('AUS','Mathew Ryan','Mathew Ryan','GK',1,'Levante'),
  ('AUS','Miloš Degenek','Miloš Degenek','DEF',2,'APOEL'),
  ('AUS','Alessandro Circati','Alessandro Circati','DEF',3,'Parma'),
  ('AUS','Jacob Italiano','Jacob Italiano','DEF',4,'GAK'),
  ('AUS','Jordan Bos','Jordan Bos','DEF',5,'Feyenoord'),
  ('AUS','Jason Geria','Jason Geria','DEF',6,'Albirex Niigata'),
  ('AUS','Mathew Leckie','Mathew Leckie','FWD',7,'Melbourne City'),
  ('AUS','Connor Metcalfe','Connor Metcalfe','MID',8,'FC St. Pauli'),
  ('AUS','Mohamed Touré','Mohamed Touré','FWD',9,'Norwich City'),
  ('AUS','Ajdin Hrustic','Ajdin Hrustic','FWD',10,'Heracles Almelo'),
  ('AUS','Awer Mabil','Awer Mabil','FWD',11,'Castellón'),
  ('AUS','Paul Izzo','Paul Izzo','GK',12,'Randers'),
  ('AUS','Aiden O''Neill','Aiden O''Neill','MID',13,'New York City FC'),
  ('AUS','Cammy Devlin','Cammy Devlin','MID',14,'Heart of Midlothian'),
  ('AUS','Kai Trewin','Kai Trewin','DEF',15,'New York City FC'),
  ('AUS','Aziz Behich','Aziz Behich','DEF',16,'Melbourne City'),
  ('AUS','Nestory Irankunda','Nestory Irankunda','FWD',17,'Watford'),
  ('AUS','Patrick Beach','Patrick Beach','GK',18,'Melbourne City'),
  ('AUS','Harry Souttar','Harry Souttar','DEF',19,'Leicester City'),
  ('AUS','Cristian Volpato','Cristian Volpato','FWD',20,'Sassuolo'),
  ('AUS','Cameron Burgess','Cameron Burgess','DEF',21,'Swansea City'),
  ('AUS','Jackson Irvine','Jackson Irvine','MID',22,'FC St. Pauli'),
  ('AUS','Nishan Velupillay','Nishan Velupillay','FWD',23,'Melbourne Victory'),
  ('AUS','Paul Okon-Engstler','Paul Okon-Engstler','MID',24,'Sydney FC'),
  ('AUS','Lucas Herrington','Lucas Herrington','DEF',25,'Colorado Rapids'),
  ('AUS','Tete Yengi','Tete Yengi','FWD',26,'Machida Zelvia'),
  ('AUT','Alexander Schlager','Alexander Schlager','GK',1,'Red Bull Salzburg'),
  ('AUT','David Affengruber','David Affengruber','DEF',2,'Elche'),
  ('AUT','Kevin Danso','Kevin Danso','DEF',3,'Tottenham Hotspur'),
  ('AUT','Xaver Schlager','Xaver Schlager','MID',4,'RB Leipzig'),
  ('AUT','Stefan Posch','Stefan Posch','DEF',5,'Mainz 05'),
  ('AUT','Nicolas Seiwald','Nicolas Seiwald','MID',6,'RB Leipzig'),
  ('AUT','Marko Arnautović','Marko Arnautović','FWD',7,'Red Star Belgrade'),
  ('AUT','David Alaba','David Alaba','DEF',8,'Real Madrid'),
  ('AUT','Marcel Sabitzer','Marcel Sabitzer','MID',9,'Borussia Dortmund'),
  ('AUT','Florian Grillitsch','Florian Grillitsch','MID',10,'Braga'),
  ('AUT','Michael Gregoritsch','Michael Gregoritsch','FWD',11,'FC Augsburg'),
  ('AUT','Florian Wiegele','Florian Wiegele','GK',12,'Viktoria Plzeň'),
  ('AUT','Patrick Pentz','Patrick Pentz','GK',13,'Brøndby'),
  ('AUT','Saša Kalajdžić','Saša Kalajdžić','FWD',14,'LASK'),
  ('AUT','Philipp Lienhart','Philipp Lienhart','DEF',15,'SC Freiburg'),
  ('AUT','Phillipp Mwene','Phillipp Mwene','DEF',16,'Mainz 05'),
  ('AUT','Carney Chukwuemeka','Carney Chukwuemeka','MID',17,'Borussia Dortmund'),
  ('AUT','Romano Schmid','Romano Schmid','MID',18,'Werder Bremen'),
  ('AUT','Konrad Laimer','Konrad Laimer','MID',20,'Bayern Munich'),
  ('AUT','Patrick Wimmer','Patrick Wimmer','FWD',21,'VfL Wolfsburg'),
  ('AUT','Alexander Prass','Alexander Prass','MID',22,'TSG Hoffenheim'),
  ('AUT','Marco Friedl','Marco Friedl','DEF',23,'Werder Bremen'),
  ('AUT','Paul Wanner','Paul Wanner','MID',24,'PSV Eindhoven'),
  ('AUT','Michael Svoboda','Michael Svoboda','DEF',25,'Venezia'),
  ('AUT','Alessandro Schöpf','Alessandro Schöpf','MID',26,'Wolfsberger AC'),
  ('BEL','Thibaut Courtois','Thibaut Courtois','GK',1,'Real Madrid'),
  ('BEL','Zeno Debast','Zeno Debast','DEF',2,'Sporting CP'),
  ('BEL','Arthur Theate','Arthur Theate','DEF',3,'Eintracht Frankfurt'),
  ('BEL','Brandon Mechele','Brandon Mechele','DEF',4,'Club Brugge'),
  ('BEL','Maxim De Cuyper','Maxim De Cuyper','DEF',5,'Brighton & Hove Albion'),
  ('BEL','Axel Witsel','Axel Witsel','MID',6,'Girona'),
  ('BEL','Kevin De Bruyne','Kevin De Bruyne','MID',7,'Napoli'),
  ('BEL','Youri Tielemans','Youri Tielemans','MID',8,'Aston Villa'),
  ('BEL','Romelu Lukaku','Romelu Lukaku','FWD',9,'Napoli'),
  ('BEL','Leandro Trossard','Leandro Trossard','FWD',10,'Arsenal'),
  ('BEL','Jérémy Doku','Jérémy Doku','FWD',11,'Manchester City'),
  ('BEL','Senne Lammens','Senne Lammens','GK',12,'Manchester United'),
  ('BEL','Mike Penders','Mike Penders','GK',13,'Strasbourg'),
  ('BEL','Dodi Lukébakio','Dodi Lukébakio','FWD',14,'Benfica'),
  ('BEL','Thomas Meunier','Thomas Meunier','DEF',15,'Lille'),
  ('BEL','Koni De Winter','Koni De Winter','DEF',16,'Milan'),
  ('BEL','Charles De Ketelaere','Charles De Ketelaere','FWD',17,'Atalanta'),
  ('BEL','Joaquin Seys','Joaquin Seys','DEF',18,'Club Brugge'),
  ('BEL','Diego Moreira','Diego Moreira','MID',19,'Strasbourg'),
  ('BEL','Hans Vanaken','Hans Vanaken','MID',20,'Club Brugge'),
  ('BEL','Timothy Castagne','Timothy Castagne','DEF',21,'Fulham'),
  ('BEL','Alexis Saelemaekers','Alexis Saelemaekers','MID',22,'Milan'),
  ('BEL','Nicolas Raskin','Nicolas Raskin','MID',23,'Rangers'),
  ('BEL','Amadou Onana','Amadou Onana','MID',24,'Aston Villa'),
  ('BEL','Nathan Ngoy','Nathan Ngoy','DEF',25,'Lille'),
  ('BEL','Matias Fernandez-Pardo','Matias Fernandez-Pardo','FWD',26,'Lille'),
  ('BIH','Nikola Vasilj','Nikola Vasilj','GK',1,'FC St. Pauli'),
  ('BIH','Nihad Mujakić','Nihad Mujakić','DEF',2,'Gaziantep'),
  ('BIH','Dennis Hadžikadunić','Dennis Hadžikadunić','DEF',3,'Sampdoria'),
  ('BIH','Tarik Muharemović','Tarik Muharemović','DEF',4,'Sassuolo'),
  ('BIH','Sead Kolašinac','Sead Kolašinac','DEF',5,'Atalanta'),
  ('BIH','Benjamin Tahirović','Benjamin Tahirović','MID',6,'Brøndby'),
  ('BIH','Amar Dedić','Amar Dedić','DEF',7,'Benfica'),
  ('BIH','Armin Gigović','Armin Gigović','MID',8,'Young Boys'),
  ('BIH','Samed Baždar','Samed Baždar','FWD',9,'Jagiellonia Białystok'),
  ('BIH','Ermedin Demirović','Ermedin Demirović','FWD',10,'VfB Stuttgart'),
  ('BIH','Edin Džeko','Edin Džeko','FWD',11,'Schalke 04'),
  ('BIH','Mladen Jurkas','Mladen Jurkas','GK',12,'Borac Banja Luka'),
  ('BIH','Ivan Bašić','Ivan Bašić','MID',13,'Astana'),
  ('BIH','Ivan Šunjić','Ivan Šunjić','MID',14,'Pafos'),
  ('BIH','Amar Memić','Amar Memić','MID',15,'Viktoria Plzeň'),
  ('BIH','Amir Hadžiahmetović','Amir Hadžiahmetović','MID',16,'Hull City'),
  ('BIH','Dženis Burnić','Dženis Burnić','MID',17,'Karlsruher SC'),
  ('BIH','Nikola Katić','Nikola Katić','DEF',18,'Schalke 04'),
  ('BIH','Kerim Alajbegović','Kerim Alajbegović','FWD',19,'Red Bull Salzburg'),
  ('BIH','Esmir Bajraktarević','Esmir Bajraktarević','FWD',20,'PSV Eindhoven'),
  ('BIH','Stjepan Radeljić','Stjepan Radeljić','DEF',21,'Rijeka'),
  ('BIH','Martin Zlomislić','Martin Zlomislić','GK',22,'Rijeka'),
  ('BIH','Haris Tabaković','Haris Tabaković','FWD',23,'Borussia Mönchengladbach'),
  ('BIH','Nidal Čelik','Nidal Čelik','DEF',24,'Lens'),
  ('BIH','Jovo Lukić','Jovo Lukić','FWD',25,'Universitatea Cluj'),
  ('BIH','Ermin Mahmić','Ermin Mahmić','MID',26,'Slovan Liberec'),
  ('BRA','Alisson','Alisson','GK',1,'Liverpool'),
  ('BRA','Wesley','Wesley','DEF',2,'Roma'),
  ('BRA','Gabriel Magalhães','Gabriel Magalhães','DEF',3,'Arsenal'),
  ('BRA','Marquinhos','Marquinhos','DEF',4,'Paris Saint-Germain'),
  ('BRA','Casemiro','Casemiro','MID',5,'Manchester United'),
  ('BRA','Alex Sandro','Alex Sandro','DEF',6,'Flamengo'),
  ('BRA','Vinícius Júnior','Vinícius Júnior','FWD',7,'Real Madrid'),
  ('BRA','Bruno Guimarães','Bruno Guimarães','MID',8,'Newcastle United'),
  ('BRA','Matheus Cunha','Matheus Cunha','FWD',9,'Manchester United'),
  ('BRA','Neymar','Neymar','FWD',10,'Santos'),
  ('BRA','Raphinha','Raphinha','FWD',11,'Barcelona'),
  ('BRA','Weverton','Weverton','GK',12,'Grêmio'),
  ('BRA','Danilo Luiz','Danilo Luiz','DEF',13,'Flamengo'),
  ('BRA','Bremer','Bremer','DEF',14,'Juventus'),
  ('BRA','Léo Pereira','Léo Pereira','DEF',15,'Flamengo'),
  ('BRA','Douglas Santos','Douglas Santos','DEF',16,'Zenit Saint Petersburg'),
  ('BRA','Fabinho','Fabinho','MID',17,'Al-Ittihad'),
  ('BRA','Danilo Santos','Danilo Santos','MID',18,'Botafogo'),
  ('BRA','Endrick','Endrick','FWD',19,'Lyon'),
  ('BRA','Lucas Paquetá','Lucas Paquetá','MID',20,'Flamengo'),
  ('BRA','Luiz Henrique','Luiz Henrique','FWD',21,'Zenit Saint Petersburg'),
  ('BRA','Gabriel Martinelli','Gabriel Martinelli','FWD',22,'Arsenal'),
  ('BRA','Ederson','Ederson','GK',23,'Fenerbahçe'),
  ('BRA','Roger Ibañez','Roger Ibañez','DEF',24,'Al-Ahli'),
  ('BRA','Igor Thiago','Igor Thiago','FWD',25,'Brentford'),
  ('BRA','Rayan','Rayan','FWD',26,'Bournemouth'),
  ('CAN','Dayne St. Clair','Dayne St. Clair','GK',1,'Inter Miami CF'),
  ('CAN','Alistair Johnston','Alistair Johnston','DEF',2,'Celtic'),
  ('CAN','Alfie Jones','Alfie Jones','DEF',3,'Middlesbrough'),
  ('CAN','Luc de Fougerolles','Luc de Fougerolles','DEF',4,'Dender'),
  ('CAN','Joel Waterman','Joel Waterman','DEF',5,'Chicago Fire FC'),
  ('CAN','Mathieu Choinière','Mathieu Choinière','MID',6,'Los Angeles FC'),
  ('CAN','Stephen Eustáquio','Stephen Eustáquio','MID',7,'Los Angeles FC'),
  ('CAN','Ismaël Koné','Ismaël Koné','MID',8,'Sassuolo'),
  ('CAN','Cyle Larin','Cyle Larin','FWD',9,'Southampton'),
  ('CAN','Jonathan David','Jonathan David','FWD',10,'Juventus'),
  ('CAN','Liam Millar','Liam Millar','MID',11,'Hull City'),
  ('CAN','Tani Oluwaseyi','Tani Oluwaseyi','FWD',12,'Villarreal'),
  ('CAN','Derek Cornelius','Derek Cornelius','DEF',13,'Rangers'),
  ('CAN','Jacob Shaffelburg','Jacob Shaffelburg','MID',14,'Los Angeles FC'),
  ('CAN','Moïse Bombito','Moïse Bombito','DEF',15,'Nice'),
  ('CAN','Maxime Crépeau','Maxime Crépeau','GK',16,'Orlando City SC'),
  ('CAN','Tajon Buchanan','Tajon Buchanan','FWD',17,'Villarreal'),
  ('CAN','Owen Goodman','Owen Goodman','GK',18,'Barnsley'),
  ('CAN','Alphonso Davies','Alphonso Davies','DEF',19,'Bayern Munich'),
  ('CAN','Ali Ahmed','Ali Ahmed','FWD',20,'Norwich City'),
  ('CAN','Jonathan Osorio','Jonathan Osorio','MID',21,'Toronto FC'),
  ('CAN','Richie Laryea','Richie Laryea','DEF',22,'Toronto FC'),
  ('CAN','Niko Sigur','Niko Sigur','DEF',23,'Hajduk Split'),
  ('CAN','Promise David','Promise David','FWD',24,'Union Saint-Gilloise'),
  ('CAN','Nathan Saliba','Nathan Saliba','MID',25,'Anderlecht'),
  ('CIV','Yahia Fofana','Yahia Fofana','GK',1,'Çaykur Rizespor'),
  ('CIV','Ousmane Diomande','Ousmane Diomande','DEF',2,'Sporting CP'),
  ('CIV','Ghislain Konan','Ghislain Konan','DEF',3,'Gil Vicente'),
  ('CIV','Jean Michaël Seri','Jean Michaël Seri','MID',4,'Maribor'),
  ('CIV','Wilfried Singo','Wilfried Singo','DEF',5,'Galatasaray'),
  ('CIV','Seko Fofana','Seko Fofana','MID',6,'Porto'),
  ('CIV','Odilon Kossounou','Odilon Kossounou','DEF',7,'Atalanta'),
  ('CIV','Franck Kessié','Franck Kessié','MID',8,'Al-Ahli'),
  ('CIV','Ange-Yoan Bonny','Ange-Yoan Bonny','FWD',9,'Inter Milan'),
  ('CIV','Simon Adingra','Simon Adingra','FWD',10,'Monaco'),
  ('CIV','Yan Diomande','Yan Diomande','FWD',11,'RB Leipzig'),
  ('CIV','Elye Wahi','Elye Wahi','FWD',12,'Nice'),
  ('CIV','Christopher Opéri','Christopher Opéri','DEF',13,'İstanbul Başakşehir'),
  ('CIV','Oumar Diakité','Oumar Diakité','FWD',14,'Cercle Brugge'),
  ('CIV','Amad Diallo','Amad Diallo','FWD',15,'Manchester United'),
  ('CIV','Mohamed Koné','Mohamed Koné','GK',16,'Charleroi'),
  ('CIV','Guéla Doué','Guéla Doué','DEF',17,'Strasbourg'),
  ('CIV','Ibrahim Sangaré','Ibrahim Sangaré','MID',18,'Nottingham Forest'),
  ('CIV','Nicolas Pépé','Nicolas Pépé','FWD',19,'Villarreal'),
  ('CIV','Emmanuel Agbadou','Emmanuel Agbadou','DEF',20,'Beşiktaş'),
  ('CIV','Evan Ndicka','Evan Ndicka','DEF',21,'Roma'),
  ('CIV','Evann Guessand','Evann Guessand','FWD',22,'Crystal Palace'),
  ('CIV','Alban Lafont','Alban Lafont','GK',23,'Panathinaikos'),
  ('CIV','Bazoumana Touré','Bazoumana Touré','FWD',24,'TSG Hoffenheim'),
  ('CIV','Parfait Guiagon','Parfait Guiagon','MID',25,'Charleroi'),
  ('CIV','Christ Inao Oulaï','Christ Inao Oulaï','MID',26,'Trabzonspor'),
  ('COD','Lionel Mpasi','Lionel Mpasi','GK',1,'Le Havre'),
  ('COD','Aaron Wan-Bissaka','Aaron Wan-Bissaka','DEF',2,'West Ham United'),
  ('COD','Steve Kapuadi','Steve Kapuadi','DEF',3,'Widzew Łódź'),
  ('COD','Axel Tuanzebe','Axel Tuanzebe','DEF',4,'Burnley'),
  ('COD','Dylan Batubinsika','Dylan Batubinsika','DEF',5,'AEL'),
  ('COD','Ngal''ayel Mukau','Ngal''ayel Mukau','MID',6,'Lille'),
  ('COD','Nathanaël Mbuku','Nathanaël Mbuku','MID',7,'Montpellier'),
  ('COD','Samuel Moutoussamy','Samuel Moutoussamy','MID',8,'Atromitos'),
  ('COD','Brian Cipenga','Brian Cipenga','FWD',9,'Castellón'),
  ('COD','Théo Bongonda','Théo Bongonda','MID',10,'Spartak Moscow'),
  ('COD','Gaël Kakuta','Gaël Kakuta','FWD',11,'AEL'),
  ('COD','Joris Kayembe','Joris Kayembe','DEF',12,'Genk'),
  ('COD','Meschak Elia','Meschak Elia','FWD',13,'Alanyaspor'),
  ('COD','Noah Sadiki','Noah Sadiki','MID',14,'Sunderland'),
  ('COD','Aaron Tshibola','Aaron Tshibola','MID',15,'Kilmarnock'),
  ('COD','Timothy Fayulu','Timothy Fayulu','GK',16,'Noah'),
  ('COD','Cédric Bakambu','Cédric Bakambu','FWD',17,'Real Betis'),
  ('COD','Charles Pickel','Charles Pickel','MID',18,'Espanyol'),
  ('COD','Fiston Mayele','Fiston Mayele','FWD',19,'Pyramids'),
  ('COD','Yoane Wissa','Yoane Wissa','FWD',20,'Newcastle United'),
  ('COD','Matthieu Epolo','Matthieu Epolo','GK',21,'Standard Liège'),
  ('COD','Chancel Mbemba','Chancel Mbemba','DEF',22,'Lille'),
  ('COD','Simon Banza','Simon Banza','FWD',23,'Al Jazira'),
  ('COD','Gédéon Kalulu','Gédéon Kalulu','DEF',24,'Aris Limassol'),
  ('COD','Edo Kayembe','Edo Kayembe','MID',25,'Watford'),
  ('COD','Arthur Masuaku','Arthur Masuaku','DEF',26,'Lens'),
  ('COL','David Ospina','David Ospina','GK',1,'Atlético Nacional'),
  ('COL','Daniel Muñoz','Daniel Muñoz','DEF',2,'Crystal Palace'),
  ('COL','Jhon Lucumí','Jhon Lucumí','DEF',3,'Bologna'),
  ('COL','Santiago Arias','Santiago Arias','DEF',4,'Independiente'),
  ('COL','Kevin Castaño','Kevin Castaño','MID',5,'River Plate'),
  ('COL','Richard Ríos','Richard Ríos','MID',6,'Benfica'),
  ('COL','Luis Díaz','Luis Díaz','FWD',7,'Bayern Munich'),
  ('COL','Jorge Carrascal','Jorge Carrascal','MID',8,'Flamengo'),
  ('COL','Jhon Córdoba','Jhon Córdoba','FWD',9,'Krasnodar'),
  ('COL','James Rodríguez','James Rodríguez','MID',10,'Minnesota United FC'),
  ('COL','Jhon Arias','Jhon Arias','MID',11,'Palmeiras'),
  ('COL','Camilo Vargas','Camilo Vargas','GK',12,'Atlas'),
  ('COL','Yerry Mina','Yerry Mina','DEF',13,'Cagliari'),
  ('COL','Gustavo Puerta','Gustavo Puerta','DEF',14,'Racing Santander'),
  ('COL','Juan Portilla','Juan Portilla','MID',15,'Athletico Paranaense'),
  ('COL','Jefferson Lerma','Jefferson Lerma','MID',16,'Crystal Palace'),
  ('COL','Johan Mojica','Johan Mojica','DEF',17,'Mallorca'),
  ('COL','Willer Ditta','Willer Ditta','DEF',18,'Cruz Azul'),
  ('COL','Cucho Hernández','Cucho Hernández','FWD',19,'Real Betis'),
  ('COL','Juan Fernando Quintero','Juan Fernando Quintero','MID',20,'River Plate'),
  ('COL','Jaminton Campaz','Jaminton Campaz','FWD',21,'Rosario Central'),
  ('COL','Deiver Machado','Deiver Machado','DEF',22,'Nantes'),
  ('COL','Davinson Sánchez','Davinson Sánchez','DEF',23,'Galatasaray'),
  ('COL','Álvaro Montero','Álvaro Montero','GK',24,'Vélez Sarsfield'),
  ('COL','Luis Suárez','Luis Suárez','FWD',25,'Sporting CP'),
  ('COL','Andrés Gómez','Andrés Gómez','FWD',26,'Vasco da Gama'),
  ('CPV','Vozinha','Vozinha','GK',1,'Chaves'),
  ('CPV','Stopira','Stopira','DEF',2,'Torreense'),
  ('CPV','Diney','Diney','DEF',3,'Al Bataeh'),
  ('CPV','Roberto Lopes','Roberto Lopes','DEF',4,'Shamrock Rovers'),
  ('CPV','Logan Costa','Logan Costa','DEF',5,'Villarreal'),
  ('CPV','Kevin Pina','Kevin Pina','MID',6,'Krasnodar'),
  ('CPV','Jovane Cabral','Jovane Cabral','MID',7,'Estrela Amadora'),
  ('CPV','João Paulo','João Paulo','MID',8,'FCSB'),
  ('CPV','Gilson Benchimol','Gilson Benchimol','FWD',9,'Akron Tolyatti'),
  ('CPV','Jamiro Monteiro','Jamiro Monteiro','MID',10,'PEC Zwolle'),
  ('CPV','Garry Rodrigues','Garry Rodrigues','MID',11,'Apollon Limassol'),
  ('CPV','Márcio Rosa','Márcio Rosa','GK',12,'Montana'),
  ('CPV','Sidny Lopes Cabral','Sidny Lopes Cabral','DEF',13,'Benfica'),
  ('CPV','Deroy Duarte','Deroy Duarte','MID',14,'Ludogorets Razgrad'),
  ('CPV','Laros Duarte','Laros Duarte','MID',15,'Puskás Akadémia'),
  ('CPV','Yannick Semedo','Yannick Semedo','MID',16,'Farense'),
  ('CPV','Willy Semedo','Willy Semedo','MID',17,'Omonia'),
  ('CPV','Telmo Arcanjo','Telmo Arcanjo','MID',18,'Vitória de Guimarães'),
  ('CPV','Dailon Livramento','Dailon Livramento','FWD',19,'Casa Pia'),
  ('CPV','Ryan Mendes','Ryan Mendes','FWD',20,'Iğdır'),
  ('CPV','Nuno da Costa','Nuno da Costa','MID',21,'İstanbul Başakşehir'),
  ('CPV','Steven Moreira','Steven Moreira','DEF',22,'Columbus Crew'),
  ('CPV','CJ dos Santos','CJ dos Santos','GK',23,'San Diego FC'),
  ('CPV','Wagner Pina','Wagner Pina','DEF',24,'Trabzonspor'),
  ('CPV','Kelvin Pires','Kelvin Pires','DEF',25,'SJK'),
  ('CPV','Hélio Varela','Hélio Varela','MID',26,'Maccabi Tel Aviv'),
  ('CRO','Dominik Livaković','Dominik Livaković','GK',1,'Dinamo Zagreb'),
  ('CRO','Josip Stanišić','Josip Stanišić','DEF',2,'Bayern Munich'),
  ('CRO','Marin Pongračić','Marin Pongračić','DEF',3,'Fiorentina'),
  ('CRO','Joško Gvardiol','Joško Gvardiol','DEF',4,'Manchester City'),
  ('CRO','Duje Ćaleta-Car','Duje Ćaleta-Car','DEF',5,'Real Sociedad'),
  ('CRO','Josip Šutalo','Josip Šutalo','DEF',6,'Ajax'),
  ('CRO','Nikola Moro','Nikola Moro','MID',7,'Bologna'),
  ('CRO','Mateo Kovačić','Mateo Kovačić','MID',8,'Manchester City'),
  ('CRO','Andrej Kramarić','Andrej Kramarić','FWD',9,'TSG Hoffenheim'),
  ('CRO','Luka Modrić','Luka Modrić','MID',10,'Milan'),
  ('CRO','Ante Budimir','Ante Budimir','FWD',11,'Osasuna'),
  ('CRO','Ivor Pandur','Ivor Pandur','GK',12,'Hull City'),
  ('CRO','Nikola Vlašić','Nikola Vlašić','MID',13,'Torino'),
  ('CRO','Ivan Perišić','Ivan Perišić','FWD',14,'PSV Eindhoven'),
  ('CRO','Mario Pašalić','Mario Pašalić','MID',15,'Atalanta'),
  ('CRO','Martin Baturina','Martin Baturina','MID',16,'Como'),
  ('CRO','Petar Sučić','Petar Sučić','MID',17,'Inter Milan'),
  ('CRO','Kristijan Jakić','Kristijan Jakić','DEF',18,'FC Augsburg'),
  ('CRO','Toni Fruk','Toni Fruk','MID',19,'Rijeka'),
  ('CRO','Igor Matanović','Igor Matanović','FWD',20,'SC Freiburg'),
  ('CRO','Luka Sučić','Luka Sučić','MID',21,'Real Sociedad'),
  ('CRO','Luka Vušković','Luka Vušković','DEF',22,'Hamburger SV'),
  ('CRO','Dominik Kotarski','Dominik Kotarski','GK',23,'Copenhagen'),
  ('CRO','Marco Pašalić','Marco Pašalić','FWD',24,'Orlando City SC'),
  ('CRO','Martin Erlić','Martin Erlić','DEF',25,'Midtjylland'),
  ('CRO','Petar Musa','Petar Musa','FWD',26,'FC Dallas'),
  ('CUW','Eloy Room','Eloy Room','GK',1,'Miami FC'),
  ('CUW','Shurandy Sambo','Shurandy Sambo','DEF',2,'Sparta Rotterdam'),
  ('CUW','Juriën Gaari','Juriën Gaari','DEF',3,'Abha'),
  ('CUW','Roshon van Eijma','Roshon van Eijma','DEF',4,'RKC Waalwijk'),
  ('CUW','Sherel Floranus','Sherel Floranus','DEF',5,'PEC Zwolle'),
  ('CUW','Godfried Roemeratoe','Godfried Roemeratoe','MID',6,'RKC Waalwijk'),
  ('CUW','Juninho Bacuna','Juninho Bacuna','MID',7,'Volendam'),
  ('CUW','Livano Comenencia','Livano Comenencia','MID',8,'Zürich'),
  ('CUW','Jürgen Locadia','Jürgen Locadia','FWD',9,'Miami FC'),
  ('CUW','Leandro Bacuna','Leandro Bacuna','MID',10,'Iğdır'),
  ('CUW','Jeremy Antonisse','Jeremy Antonisse','FWD',11,'Kifisia'),
  ('CUW','Sontje Hansen','Sontje Hansen','FWD',12,'Middlesbrough'),
  ('CUW','Tyrese Noslin','Tyrese Noslin','FWD',13,'Telstar'),
  ('CUW','Kenji Gorré','Kenji Gorré','FWD',14,'Maccabi Haifa'),
  ('CUW','Ar''jany Martha','Ar''jany Martha','MID',15,'Rotherham United'),
  ('CUW','Jearl Margaritha','Jearl Margaritha','FWD',16,'Beveren'),
  ('CUW','Brandley Kuwas','Brandley Kuwas','FWD',17,'Volendam'),
  ('CUW','Armando Obispo','Armando Obispo','DEF',18,'PSV Eindhoven'),
  ('CUW','Gervane Kastaneer','Gervane Kastaneer','FWD',19,'Terengganu'),
  ('CUW','Joshua Brenet','Joshua Brenet','DEF',20,'Kayserispor'),
  ('CUW','Tahith Chong','Tahith Chong','MID',21,'Sheffield United'),
  ('CUW','Kevin Felida','Kevin Felida','MID',22,'Den Bosch'),
  ('CUW','Riechedly Bazoer','Riechedly Bazoer','DEF',23,'Konyaspor'),
  ('CUW','Deveron Fonville','Deveron Fonville','DEF',24,'NEC'),
  ('CUW','Tyrick Bodak','Tyrick Bodak','GK',25,'Telstar'),
  ('CUW','Trevor Doornbusch','Trevor Doornbusch','GK',26,'VVV-Venlo'),
  ('CZE','Matěj Kovář','Matěj Kovář','GK',1,'PSV Eindhoven'),
  ('CZE','David Zima','David Zima','DEF',2,'Slavia Prague'),
  ('CZE','Tomáš Holeš','Tomáš Holeš','DEF',3,'Slavia Prague'),
  ('CZE','Robin Hranáč','Robin Hranáč','DEF',4,'TSG Hoffenheim'),
  ('CZE','Vladimír Coufal','Vladimír Coufal','DEF',5,'TSG Hoffenheim'),
  ('CZE','Štěpán Chaloupek','Štěpán Chaloupek','DEF',6,'Slavia Prague'),
  ('CZE','Ladislav Krejčí','Ladislav Krejčí','DEF',7,'Wolverhampton Wanderers'),
  ('CZE','Vladimír Darida','Vladimír Darida','MID',8,'Hradec Králové'),
  ('CZE','Adam Hložek','Adam Hložek','FWD',9,'TSG Hoffenheim'),
  ('CZE','Patrik Schick','Patrik Schick','FWD',10,'Bayer Leverkusen'),
  ('CZE','Jan Kuchta','Jan Kuchta','FWD',11,'Sparta Prague'),
  ('CZE','Lukáš Červ','Lukáš Červ','MID',12,'Viktoria Plzeň'),
  ('CZE','Mojmír Chytil','Mojmír Chytil','FWD',13,'Slavia Prague'),
  ('CZE','David Jurásek','David Jurásek','DEF',14,'Slavia Prague'),
  ('CZE','Pavel Šulc','Pavel Šulc','FWD',15,'Lyon'),
  ('CZE','Jindřich Staněk','Jindřich Staněk','GK',16,'Slavia Prague'),
  ('CZE','Lukáš Provod','Lukáš Provod','MID',17,'Slavia Prague'),
  ('CZE','Michal Sadílek','Michal Sadílek','MID',18,'Slavia Prague'),
  ('CZE','Tomáš Chorý','Tomáš Chorý','FWD',19,'Slavia Prague'),
  ('CZE','Jaroslav Zelený','Jaroslav Zelený','DEF',20,'Sparta Prague'),
  ('CZE','David Douděra','David Douděra','DEF',21,'Slavia Prague'),
  ('CZE','Tomáš Souček','Tomáš Souček','MID',22,'West Ham United'),
  ('CZE','Lukáš Horníček','Lukáš Horníček','GK',23,'Braga'),
  ('CZE','Alexandr Sojka','Alexandr Sojka','MID',24,'Viktoria Plzeň'),
  ('CZE','Hugo Sochůrek','Hugo Sochůrek','MID',25,'Sparta Prague'),
  ('CZE','Denis Višinský','Denis Višinský','FWD',26,'Viktoria Plzeň'),
  ('ECU','Hernán Galíndez','Hernán Galíndez','GK',1,'Huracán'),
  ('ECU','Félix Torres','Félix Torres','DEF',2,'Internacional'),
  ('ECU','Piero Hincapié','Piero Hincapié','DEF',3,'Arsenal'),
  ('ECU','Joel Ordóñez','Joel Ordóñez','DEF',4,'Club Brugge'),
  ('ECU','Jordy Alcívar','Jordy Alcívar','MID',5,'Independiente del Valle'),
  ('ECU','Willian Pacho','Willian Pacho','DEF',6,'Paris Saint-Germain'),
  ('ECU','Pervis Estupiñán','Pervis Estupiñán','DEF',7,'Milan'),
  ('ECU','Anthony Valencia','Anthony Valencia','MID',8,'Antwerp'),
  ('ECU','John Yeboah','John Yeboah','FWD',9,'Venezia'),
  ('ECU','Kendry Páez','Kendry Páez','MID',10,'River Plate'),
  ('ECU','Kevin Rodríguez','Kevin Rodríguez','FWD',11,'Union Saint-Gilloise'),
  ('ECU','Moisés Ramírez','Moisés Ramírez','GK',12,'Kifisia'),
  ('ECU','Enner Valencia','Enner Valencia','FWD',13,'Pachuca'),
  ('ECU','Alan Minda','Alan Minda','MID',14,'Atlético Mineiro'),
  ('ECU','Pedro Vite','Pedro Vite','MID',15,'UNAM'),
  ('ECU','Jordy Caicedo','Jordy Caicedo','FWD',16,'Huracán'),
  ('ECU','Ángelo Preciado','Ángelo Preciado','DEF',17,'Atlético Mineiro'),
  ('ECU','Denil Castillo','Denil Castillo','MID',18,'Midtjylland'),
  ('ECU','Gonzalo Plata','Gonzalo Plata','FWD',19,'Flamengo'),
  ('ECU','Nilson Angulo','Nilson Angulo','FWD',20,'Sunderland'),
  ('ECU','Alan Franco','Alan Franco','MID',21,'Atlético Mineiro'),
  ('ECU','Gonzalo Valle','Gonzalo Valle','GK',22,'LDU Quito'),
  ('ECU','Moisés Caicedo','Moisés Caicedo','MID',23,'Chelsea'),
  ('ECU','Jeremy Arévalo','Jeremy Arévalo','FWD',24,'VfB Stuttgart'),
  ('ECU','Jackson Porozo','Jackson Porozo','DEF',25,'Tijuana'),
  ('ECU','Yaimar Medina','Yaimar Medina','DEF',26,'Genk'),
  ('EGY','Mohamed El Shenawy','Mohamed El Shenawy','GK',1,'Al Ahly'),
  ('EGY','Yasser Ibrahim','Yasser Ibrahim','DEF',2,'Al Ahly'),
  ('EGY','Mohamed Hany','Mohamed Hany','DEF',3,'Al Ahly'),
  ('EGY','Hossam Abdelmaguid','Hossam Abdelmaguid','DEF',4,'Zamalek'),
  ('EGY','Ramy Rabia','Ramy Rabia','DEF',5,'Al Ain'),
  ('EGY','Mohamed Abdelmonem','Mohamed Abdelmonem','DEF',6,'Nice'),
  ('EGY','Trézéguet','Trézéguet','FWD',7,'Al Ahly'),
  ('EGY','Emam Ashour','Emam Ashour','MID',8,'Al Ahly'),
  ('EGY','Hamza Abdelkarim','Hamza Abdelkarim','FWD',9,'Barcelona'),
  ('EGY','Mohamed Salah','Mohamed Salah','FWD',10,'Liverpool'),
  ('EGY','Mostafa Ziko','Mostafa Ziko','MID',11,'Pyramids'),
  ('EGY','Haissem Hassan','Haissem Hassan','FWD',12,'Oviedo'),
  ('EGY','Ahmed Fatouh','Ahmed Fatouh','DEF',13,'Zamalek'),
  ('EGY','Hamdy Fathy','Hamdy Fathy','MID',14,'Al-Wakrah'),
  ('EGY','Karim Hafez','Karim Hafez','DEF',15,'Pyramids'),
  ('EGY','El Mahdy Soliman','El Mahdy Soliman','GK',16,'Zamalek'),
  ('EGY','Mohanad Lasheen','Mohanad Lasheen','MID',17,'Pyramids'),
  ('EGY','Nabil Emad','Nabil Emad','MID',18,'Al-Najma'),
  ('EGY','Marwan Attia','Marwan Attia','MID',19,'Al Ahly'),
  ('EGY','Ibrahim Adel','Ibrahim Adel','FWD',20,'Nordsjælland'),
  ('EGY','Mahmoud Saber','Mahmoud Saber','MID',21,'ZED'),
  ('EGY','Omar Marmoush','Omar Marmoush','FWD',22,'Manchester City'),
  ('EGY','Mostafa Shobeir','Mostafa Shobeir','GK',23,'Al Ahly'),
  ('EGY','Tarek Alaa','Tarek Alaa','DEF',24,'ZED'),
  ('EGY','Zizo','Zizo','FWD',25,'Al Ahly'),
  ('EGY','Mohamed Alaa','Mohamed Alaa','GK',26,'El Gouna'),
  ('ENG','Jordan Pickford','Jordan Pickford','GK',1,'Everton'),
  ('ENG','Ezri Konsa','Ezri Konsa','DEF',2,'Aston Villa'),
  ('ENG','Nico O''Reilly','Nico O''Reilly','DEF',3,'Manchester City'),
  ('ENG','Declan Rice','Declan Rice','MID',4,'Arsenal'),
  ('ENG','John Stones','John Stones','DEF',5,'Manchester City'),
  ('ENG','Marc Guéhi','Marc Guéhi','DEF',6,'Manchester City'),
  ('ENG','Bukayo Saka','Bukayo Saka','FWD',7,'Arsenal'),
  ('ENG','Elliot Anderson','Elliot Anderson','MID',8,'Nottingham Forest'),
  ('ENG','Harry Kane','Harry Kane','FWD',9,'Bayern Munich'),
  ('ENG','Jude Bellingham','Jude Bellingham','MID',10,'Real Madrid'),
  ('ENG','Marcus Rashford','Marcus Rashford','FWD',11,'Barcelona'),
  ('ENG','Tino Livramento','Tino Livramento','DEF',12,'Newcastle United'),
  ('ENG','Dean Henderson','Dean Henderson','GK',13,'Crystal Palace'),
  ('ENG','Jordan Henderson','Jordan Henderson','MID',14,'Brentford'),
  ('ENG','Dan Burn','Dan Burn','DEF',15,'Newcastle United'),
  ('ENG','Kobbie Mainoo','Kobbie Mainoo','MID',16,'Manchester United'),
  ('ENG','Morgan Rogers','Morgan Rogers','MID',17,'Aston Villa'),
  ('ENG','Anthony Gordon','Anthony Gordon','FWD',18,'Newcastle United'),
  ('ENG','Ollie Watkins','Ollie Watkins','FWD',19,'Aston Villa'),
  ('ENG','Noni Madueke','Noni Madueke','FWD',20,'Arsenal'),
  ('ENG','Eberechi Eze','Eberechi Eze','MID',21,'Arsenal'),
  ('ENG','Ivan Toney','Ivan Toney','FWD',22,'Al-Ahli'),
  ('ENG','James Trafford','James Trafford','GK',23,'Manchester City'),
  ('ENG','Reece James','Reece James','DEF',24,'Chelsea'),
  ('ENG','Djed Spence','Djed Spence','DEF',25,'Tottenham Hotspur'),
  ('ENG','Jarell Quansah','Jarell Quansah','DEF',26,'Bayer Leverkusen'),
  ('ESP','David Raya','David Raya','GK',1,'Arsenal'),
  ('ESP','Marc Pubill','Marc Pubill','DEF',2,'Atlético Madrid'),
  ('ESP','Álex Grimaldo','Álex Grimaldo','DEF',3,'Bayer Leverkusen'),
  ('ESP','Eric García','Eric García','DEF',4,'Barcelona'),
  ('ESP','Marcos Llorente','Marcos Llorente','DEF',5,'Atlético Madrid'),
  ('ESP','Mikel Merino','Mikel Merino','MID',6,'Arsenal'),
  ('ESP','Ferran Torres','Ferran Torres','FWD',7,'Barcelona'),
  ('ESP','Fabián Ruiz','Fabián Ruiz','MID',8,'Paris Saint-Germain'),
  ('ESP','Gavi','Gavi','MID',9,'Barcelona'),
  ('ESP','Dani Olmo','Dani Olmo','FWD',10,'Barcelona'),
  ('ESP','Yéremy Pino','Yéremy Pino','FWD',11,'Crystal Palace'),
  ('ESP','Pedro Porro','Pedro Porro','DEF',12,'Tottenham Hotspur'),
  ('ESP','Joan Garcia','Joan Garcia','GK',13,'Barcelona'),
  ('ESP','Aymeric Laporte','Aymeric Laporte','DEF',14,'Athletic Bilbao'),
  ('ESP','Álex Baena','Álex Baena','MID',15,'Atlético Madrid'),
  ('ESP','Rodri','Rodri','MID',16,'Manchester City'),
  ('ESP','Nico Williams','Nico Williams','FWD',17,'Athletic Bilbao'),
  ('ESP','Martín Zubimendi','Martín Zubimendi','MID',18,'Arsenal'),
  ('ESP','Lamine Yamal','Lamine Yamal','FWD',19,'Barcelona'),
  ('ESP','Pedri','Pedri','MID',20,'Barcelona'),
  ('ESP','Mikel Oyarzabal','Mikel Oyarzabal','FWD',21,'Real Sociedad'),
  ('ESP','Pau Cubarsí','Pau Cubarsí','DEF',22,'Barcelona'),
  ('ESP','Unai Simón','Unai Simón','GK',23,'Athletic Bilbao'),
  ('ESP','Marc Cucurella','Marc Cucurella','DEF',24,'Chelsea'),
  ('ESP','Víctor Muñoz','Víctor Muñoz','FWD',25,'Osasuna'),
  ('ESP','Borja Iglesias','Borja Iglesias','FWD',26,'Celta Vigo'),
  ('FRA','Brice Samba','Brice Samba','GK',1,'Rennes'),
  ('FRA','Malo Gusto','Malo Gusto','DEF',2,'Chelsea'),
  ('FRA','Lucas Digne','Lucas Digne','DEF',3,'Aston Villa'),
  ('FRA','Dayot Upamecano','Dayot Upamecano','DEF',4,'Bayern Munich'),
  ('FRA','Jules Koundé','Jules Koundé','DEF',5,'Barcelona'),
  ('FRA','Manu Koné','Manu Koné','MID',6,'Roma'),
  ('FRA','Ousmane Dembélé','Ousmane Dembélé','FWD',7,'Paris Saint-Germain'),
  ('FRA','Aurélien Tchouaméni','Aurélien Tchouaméni','MID',8,'Real Madrid'),
  ('FRA','Marcus Thuram','Marcus Thuram','FWD',9,'Inter Milan'),
  ('FRA','Kylian Mbappé','Kylian Mbappé','FWD',10,'Real Madrid'),
  ('FRA','Michael Olise','Michael Olise','FWD',11,'Bayern Munich'),
  ('FRA','Bradley Barcola','Bradley Barcola','FWD',12,'Paris Saint-Germain'),
  ('FRA','N''Golo Kanté','N''Golo Kanté','MID',13,'Fenerbahçe'),
  ('FRA','Adrien Rabiot','Adrien Rabiot','MID',14,'Milan'),
  ('FRA','Ibrahima Konaté','Ibrahima Konaté','DEF',15,'Liverpool'),
  ('FRA','Mike Maignan','Mike Maignan','GK',16,'Milan'),
  ('FRA','William Saliba','William Saliba','DEF',17,'Arsenal'),
  ('FRA','Warren Zaïre-Emery','Warren Zaïre-Emery','MID',18,'Paris Saint-Germain'),
  ('FRA','Théo Hernandez','Théo Hernandez','DEF',19,'Al-Hilal'),
  ('FRA','Désiré Doué','Désiré Doué','FWD',20,'Paris Saint-Germain'),
  ('FRA','Lucas Hernandez','Lucas Hernandez','DEF',21,'Paris Saint-Germain'),
  ('FRA','Jean-Philippe Mateta','Jean-Philippe Mateta','FWD',22,'Crystal Palace'),
  ('FRA','Robin Risser','Robin Risser','GK',23,'Lens'),
  ('FRA','Rayan Cherki','Rayan Cherki','MID',24,'Manchester City'),
  ('FRA','Maghnes Akliouche','Maghnes Akliouche','MID',25,'Monaco'),
  ('FRA','Maxence Lacroix','Maxence Lacroix','DEF',26,'Crystal Palace'),
  ('GER','Manuel Neuer','Manuel Neuer','GK',1,'Bayern Munich'),
  ('GER','Antonio Rüdiger','Antonio Rüdiger','DEF',2,'Real Madrid'),
  ('GER','Waldemar Anton','Waldemar Anton','DEF',3,'Borussia Dortmund'),
  ('GER','Jonathan Tah','Jonathan Tah','DEF',4,'Bayern Munich'),
  ('GER','Aleksandar Pavlović','Aleksandar Pavlović','MID',5,'Bayern Munich'),
  ('GER','Joshua Kimmich','Joshua Kimmich','DEF',6,'Bayern Munich'),
  ('GER','Kai Havertz','Kai Havertz','FWD',7,'Arsenal'),
  ('GER','Leon Goretzka','Leon Goretzka','MID',8,'Bayern Munich'),
  ('GER','Jamie Leweling','Jamie Leweling','MID',9,'VfB Stuttgart'),
  ('GER','Jamal Musiala','Jamal Musiala','MID',10,'Bayern Munich'),
  ('GER','Nick Woltemade','Nick Woltemade','FWD',11,'Newcastle United'),
  ('GER','Oliver Baumann','Oliver Baumann','GK',12,'TSG Hoffenheim'),
  ('GER','Pascal Groß','Pascal Groß','MID',13,'Brighton & Hove Albion'),
  ('GER','Maximilian Beier','Maximilian Beier','FWD',14,'Borussia Dortmund'),
  ('GER','Nico Schlotterbeck','Nico Schlotterbeck','DEF',15,'Borussia Dortmund'),
  ('GER','Angelo Stiller','Angelo Stiller','MID',16,'VfB Stuttgart'),
  ('GER','Florian Wirtz','Florian Wirtz','MID',17,'Liverpool'),
  ('GER','Nathaniel Brown','Nathaniel Brown','DEF',18,'Eintracht Frankfurt'),
  ('GER','Leroy Sané','Leroy Sané','MID',19,'Galatasaray'),
  ('GER','Nadiem Amiri','Nadiem Amiri','MID',20,'Mainz 05'),
  ('GER','Alexander Nübel','Alexander Nübel','GK',21,'VfB Stuttgart'),
  ('GER','David Raum','David Raum','DEF',22,'RB Leipzig'),
  ('GER','Felix Nmecha','Felix Nmecha','MID',23,'Borussia Dortmund'),
  ('GER','Malick Thiaw','Malick Thiaw','DEF',24,'Newcastle United'),
  ('GER','Lennart Karl','Lennart Karl','MID',25,'Bayern Munich'),
  ('GER','Deniz Undav','Deniz Undav','FWD',26,'VfB Stuttgart'),
  ('GHA','Lawrence Ati-Zigi','Lawrence Ati-Zigi','GK',1,'St. Gallen'),
  ('GHA','Alidu Seidu','Alidu Seidu','DEF',2,'Rennes'),
  ('GHA','Caleb Yirenkyi','Caleb Yirenkyi','MID',3,'Nordsjælland'),
  ('GHA','Jonas Adjetey','Jonas Adjetey','DEF',4,'VfL Wolfsburg'),
  ('GHA','Thomas Partey','Thomas Partey','MID',5,'Villarreal'),
  ('GHA','Abdul Mumin','Abdul Mumin','DEF',6,'Rayo Vallecano'),
  ('GHA','Abdul Fatawu','Abdul Fatawu','FWD',7,'Leicester City'),
  ('GHA','Kwasi Sibo','Kwasi Sibo','MID',8,'Oviedo'),
  ('GHA','Jordan Ayew','Jordan Ayew','FWD',9,'Leicester City'),
  ('GHA','Brandon Thomas-Asante','Brandon Thomas-Asante','FWD',10,'Coventry City'),
  ('GHA','Antoine Semenyo','Antoine Semenyo','MID',11,'Manchester City'),
  ('GHA','Joseph Anang','Joseph Anang','GK',12,'St Patrick''s Athletic'),
  ('GHA','Christopher Bonsu Baah','Christopher Bonsu Baah','FWD',13,'Al-Qadsiah'),
  ('GHA','Gideon Mensah','Gideon Mensah','DEF',14,'Auxerre'),
  ('GHA','Elisha Owusu','Elisha Owusu','MID',15,'Auxerre'),
  ('GHA','Benjamin Asare','Benjamin Asare','GK',16,'Hearts of Oak'),
  ('GHA','Abdul Rahman Baba','Abdul Rahman Baba','DEF',17,'PAOK'),
  ('GHA','Jerome Opoku','Jerome Opoku','DEF',18,'İstanbul Başakşehir'),
  ('GHA','Iñaki Williams','Iñaki Williams','FWD',19,'Athletic Bilbao'),
  ('GHA','Augustine Boakye','Augustine Boakye','MID',20,'Saint-Étienne'),
  ('GHA','Kojo Peprah Oppong','Kojo Peprah Oppong','DEF',21,'Nice'),
  ('GHA','Kamaldeen Sulemana','Kamaldeen Sulemana','FWD',22,'Atalanta'),
  ('GHA','Derrick Luckassen','Derrick Luckassen','DEF',23,'Pafos'),
  ('GHA','Ernest Nuamah','Ernest Nuamah','FWD',24,'Lyon'),
  ('GHA','Prince Kwabena Adu','Prince Kwabena Adu','FWD',25,'Viktoria Plzeň'),
  ('GHA','Marvin Senaya','Marvin Senaya','DEF',26,'Auxerre'),
  ('HAI','Johny Placide','Johny Placide','GK',1,'Bastia'),
  ('HAI','Carlens Arcus','Carlens Arcus','DEF',2,'Angers'),
  ('HAI','Keeto Thermoncy','Keeto Thermoncy','DEF',3,'Young Boys'),
  ('HAI','Ricardo Adé','Ricardo Adé','DEF',4,'LDU Quito'),
  ('HAI','Hannes Delcroix','Hannes Delcroix','DEF',5,'Lugano'),
  ('HAI','Carl Sainté','Carl Sainté','MID',6,'El Paso Locomotive FC'),
  ('HAI','Derrick Etienne Jr.','Derrick Etienne Jr.','FWD',7,'Toronto FC'),
  ('HAI','Martin Expérience','Martin Expérience','DEF',8,'Nancy'),
  ('HAI','Duckens Nazon','Duckens Nazon','FWD',9,'Esteghlal'),
  ('HAI','Jean-Ricner Bellegarde','Jean-Ricner Bellegarde','MID',10,'Wolverhampton Wanderers'),
  ('HAI','Louicius Deedson','Louicius Deedson','FWD',11,'FC Dallas'),
  ('HAI','Alexandre Pierre','Alexandre Pierre','GK',12,'Sochaux'),
  ('HAI','Duke Lacroix','Duke Lacroix','DEF',13,'Colorado Springs Switchbacks FC'),
  ('HAI','Leverton Pierre','Leverton Pierre','MID',14,'Vizela'),
  ('HAI','Ruben Providence','Ruben Providence','FWD',15,'Almere City'),
  ('HAI','Lenny Joseph','Lenny Joseph','FWD',16,'Ferencváros'),
  ('HAI','Danley Jean Jacques','Danley Jean Jacques','MID',17,'Philadelphia Union'),
  ('HAI','Wilson Isidor','Wilson Isidor','FWD',18,'Sunderland'),
  ('HAI','Yassin Fortuné','Yassin Fortuné','FWD',19,'Vizela'),
  ('HAI','Frantzdy Pierrot','Frantzdy Pierrot','FWD',20,'Çaykur Rizespor'),
  ('HAI','Josué Casimir','Josué Casimir','FWD',21,'Auxerre'),
  ('HAI','Jean-Kévin Duverne','Jean-Kévin Duverne','DEF',22,'Gent'),
  ('HAI','Josué Duverger','Josué Duverger','GK',23,'Cosmos Koblenz'),
  ('HAI','Wilguens Paugain','Wilguens Paugain','DEF',24,'Zulte Waregem'),
  ('HAI','Dominique Simon','Dominique Simon','MID',25,'Tatran Prešov'),
  ('HAI','Woodensky Pierre','Woodensky Pierre','MID',26,'Violette'),
  ('IRN','Alireza Beiranvand','Alireza Beiranvand','GK',1,'Tractor'),
  ('IRN','Saleh Hardani','Saleh Hardani','DEF',2,'Esteghlal'),
  ('IRN','Ehsan Hajsafi','Ehsan Hajsafi','DEF',3,'Sepahan'),
  ('IRN','Shojae Khalilzadeh','Shojae Khalilzadeh','DEF',4,'Tractor'),
  ('IRN','Milad Mohammadi','Milad Mohammadi','DEF',5,'Persepolis'),
  ('IRN','Saeid Ezatolahi','Saeid Ezatolahi','MID',6,'Shabab Al Ahli'),
  ('IRN','Alireza Jahanbakhsh','Alireza Jahanbakhsh','MID',7,'Dender'),
  ('IRN','Mohammad Mohebi','Mohammad Mohebi','MID',8,'Rostov'),
  ('IRN','Mehdi Taremi','Mehdi Taremi','FWD',9,'Olympiacos'),
  ('IRN','Mehdi Ghayedi','Mehdi Ghayedi','FWD',10,'Al Nasr'),
  ('IRN','Ali Alipour','Ali Alipour','FWD',11,'Persepolis'),
  ('IRN','Payam Niazmand','Payam Niazmand','GK',12,'Persepolis'),
  ('IRN','Hossein Kanaanizadegan','Hossein Kanaanizadegan','DEF',13,'Persepolis'),
  ('IRN','Saman Ghoddos','Saman Ghoddos','MID',14,'Kalba'),
  ('IRN','Rouzbeh Cheshmi','Rouzbeh Cheshmi','MID',15,'Esteghlal'),
  ('IRN','Mehdi Torabi','Mehdi Torabi','MID',16,'Tractor'),
  ('IRN','Aria Yousefi','Aria Yousefi','DEF',17,'Sepahan'),
  ('IRN','Amirhossein Hosseinzadeh','Amirhossein Hosseinzadeh','FWD',18,'Tractor'),
  ('IRN','Ali Nemati','Ali Nemati','DEF',19,'Foolad'),
  ('IRN','Shahriyar Moghanlou','Shahriyar Moghanlou','FWD',20,'Kalba'),
  ('IRN','Mohammad Ghorbani','Mohammad Ghorbani','MID',21,'Al Wahda'),
  ('IRN','Hossein Hosseini','Hossein Hosseini','GK',22,'Sepahan'),
  ('IRN','Ramin Rezaeian','Ramin Rezaeian','DEF',23,'Foolad'),
  ('IRN','Dennis Eckert','Dennis Eckert','FWD',24,'Standard Liège'),
  ('IRN','Danial Eiri','Danial Eiri','DEF',25,'Malavan'),
  ('IRN','Amirmohammad Razzaghinia','Amirmohammad Razzaghinia','MID',26,'Esteghlal'),
  ('IRQ','Fahad Talib','Fahad Talib','GK',1,'Al-Talaba'),
  ('IRQ','Rebin Sulaka','Rebin Sulaka','DEF',2,'Port'),
  ('IRQ','Hussein Ali','Hussein Ali','DEF',3,'Pogoń Szczecin'),
  ('IRQ','Zaid Tahseen','Zaid Tahseen','DEF',4,'Pakhtakor'),
  ('IRQ','Akam Hashim','Akam Hashim','DEF',5,'Al-Zawraa'),
  ('IRQ','Manaf Younis','Manaf Younis','DEF',6,'Al-Shorta'),
  ('IRQ','Youssef Amyn','Youssef Amyn','MID',7,'AEK Larnaca'),
  ('IRQ','Ibrahim Bayesh','Ibrahim Bayesh','MID',8,'Al Dhafra'),
  ('IRQ','Ali Al-Hamadi','Ali Al-Hamadi','FWD',9,'Luton Town'),
  ('IRQ','Mohanad Ali','Mohanad Ali','FWD',10,'Dibba'),
  ('IRQ','Ahmed Qasem','Ahmed Qasem','FWD',11,'Nashville SC'),
  ('IRQ','Jalal Hassan','Jalal Hassan','GK',12,'Al-Zawraa'),
  ('IRQ','Ali Yousif','Ali Yousif','FWD',13,'Al-Talaba'),
  ('IRQ','Zidane Iqbal','Zidane Iqbal','MID',14,'Utrecht'),
  ('IRQ','Ahmed Yahya','Ahmed Yahya','DEF',15,'Al-Shorta'),
  ('IRQ','Amir Al-Ammari','Amir Al-Ammari','MID',16,'Cracovia'),
  ('IRQ','Ali Jasim','Ali Jasim','FWD',17,'Al-Najma'),
  ('IRQ','Aymen Hussein','Aymen Hussein','FWD',18,'Al-Karma'),
  ('IRQ','Kevin Yakob','Kevin Yakob','MID',19,'AGF'),
  ('IRQ','Aimar Sher','Aimar Sher','MID',20,'Sarpsborg 08'),
  ('IRQ','Marko Farji','Marko Farji','FWD',21,'Venezia'),
  ('IRQ','Ahmed Basil','Ahmed Basil','GK',22,'Al-Shorta'),
  ('IRQ','Merchas Doski','Merchas Doski','DEF',23,'Viktoria Plzeň'),
  ('IRQ','Zaid Ismail','Zaid Ismail','MID',24,'Al-Talaba'),
  ('IRQ','Mustafa Saadoon','Mustafa Saadoon','DEF',25,'Al-Shorta'),
  ('IRQ','Frans Putros','Frans Putros','DEF',26,'Persib'),
  ('JOR','Yazeed Abulaila','Yazeed Abulaila','GK',1,'Al-Hussein'),
  ('JOR','Mohammad Abu Hashish','Mohammad Abu Hashish','DEF',2,'Al-Karma'),
  ('JOR','Abdallah Nasib','Abdallah Nasib','DEF',3,'Al-Zawraa'),
  ('JOR','Husam Abu Dahab','Husam Abu Dahab','DEF',4,'Al-Faisaly'),
  ('JOR','Yazan Al-Arab','Yazan Al-Arab','DEF',5,'FC Seoul'),
  ('JOR','Amer Jamous','Amer Jamous','MID',6,'Al-Zawraa'),
  ('JOR','Mohammad Abu Zrayq','Mohammad Abu Zrayq','FWD',7,'Raja Casablanca'),
  ('JOR','Noor Al-Rawabdeh','Noor Al-Rawabdeh','MID',8,'Selangor'),
  ('JOR','Ali Olwan','Ali Olwan','FWD',9,'Al-Sailiya'),
  ('JOR','Musa Al-Taamari','Musa Al-Taamari','FWD',10,'Rennes'),
  ('JOR','Odeh Al-Fakhouri','Odeh Al-Fakhouri','FWD',11,'Pyramids'),
  ('JOR','Nour Bani Attiah','Nour Bani Attiah','GK',12,'Al-Faisaly'),
  ('JOR','Mahmoud Al-Mardi','Mahmoud Al-Mardi','FWD',13,'Al-Hussein'),
  ('JOR','Rajaei Ayed','Rajaei Ayed','MID',14,'Al-Hussein'),
  ('JOR','Ibrahim Sadeh','Ibrahim Sadeh','MID',15,'Al-Karma'),
  ('JOR','Mo Abualnadi','Mo Abualnadi','DEF',16,'Selangor'),
  ('JOR','Salim Obaid','Salim Obaid','DEF',17,'Al-Hussein'),
  ('JOR','Ibrahim Sabra','Ibrahim Sabra','FWD',18,'Lokomotiva Zagreb'),
  ('JOR','Saed Al-Rosan','Saed Al-Rosan','DEF',19,'Al-Hussein'),
  ('JOR','Mohannad Abu Taha','Mohannad Abu Taha','MID',20,'Al-Quwa Al-Jawiya'),
  ('JOR','Nizar Al-Rashdan','Nizar Al-Rashdan','MID',21,'Qatar SC'),
  ('JOR','Abdallah Al-Fakhouri','Abdallah Al-Fakhouri','GK',22,'Al-Wehdat'),
  ('JOR','Ihsan Haddad','Ihsan Haddad','DEF',23,'Al-Hussein'),
  ('JOR','Ali Azaizeh','Ali Azaizeh','FWD',24,'Al-Shabab'),
  ('JOR','Mohammad Al-Dawoud','Mohammad Al-Dawoud','MID',25,'Al-Wehdat'),
  ('JOR','Anas Badawi','Anas Badawi','DEF',26,'Al-Faisaly'),
  ('JPN','Zion Suzuki','Zion Suzuki','GK',1,'Parma'),
  ('JPN','Yukinari Sugawara','Yukinari Sugawara','DEF',2,'Werder Bremen'),
  ('JPN','Shōgo Taniguchi','Shōgo Taniguchi','DEF',3,'Sint-Truiden'),
  ('JPN','Kō Itakura','Kō Itakura','DEF',4,'Ajax'),
  ('JPN','Yūto Nagatomo','Yūto Nagatomo','DEF',5,'FC Tokyo'),
  ('JPN','Wataru Endo','Wataru Endo','MID',6,'Liverpool'),
  ('JPN','Ao Tanaka','Ao Tanaka','MID',7,'Leeds United'),
  ('JPN','Takefusa Kubo','Takefusa Kubo','MID',8,'Real Sociedad'),
  ('JPN','Keisuke Gotō','Keisuke Gotō','FWD',9,'Sint-Truiden'),
  ('JPN','Ritsu Dōan','Ritsu Dōan','MID',10,'Eintracht Frankfurt'),
  ('JPN','Daizen Maeda','Daizen Maeda','MID',11,'Celtic'),
  ('JPN','Keisuke Ōsako','Keisuke Ōsako','GK',12,'Sanfrecce Hiroshima'),
  ('JPN','Keito Nakamura','Keito Nakamura','MID',13,'Reims'),
  ('JPN','Junya Itō','Junya Itō','MID',14,'Genk'),
  ('JPN','Daichi Kamada','Daichi Kamada','MID',15,'Crystal Palace'),
  ('JPN','Tsuyoshi Watanabe','Tsuyoshi Watanabe','DEF',16,'Feyenoord'),
  ('JPN','Yuito Suzuki','Yuito Suzuki','MID',17,'SC Freiburg'),
  ('JPN','Ayase Ueda','Ayase Ueda','FWD',18,'Feyenoord'),
  ('JPN','Kōki Ogawa','Kōki Ogawa','FWD',19,'NEC'),
  ('JPN','Ayumu Seko','Ayumu Seko','DEF',20,'Le Havre'),
  ('JPN','Hiroki Itō','Hiroki Itō','DEF',21,'Bayern Munich'),
  ('JPN','Takehiro Tomiyasu','Takehiro Tomiyasu','DEF',22,'Ajax'),
  ('JPN','Tomoki Hayakawa','Tomoki Hayakawa','GK',23,'Kashima Antlers'),
  ('JPN','Kaishū Sano','Kaishū Sano','MID',24,'Mainz 05'),
  ('JPN','Junnosuke Suzuki','Junnosuke Suzuki','DEF',25,'Copenhagen'),
  ('JPN','Kento Shiogai','Kento Shiogai','FWD',26,'VfL Wolfsburg'),
  ('KOR','Kim Seung-gyu','Kim Seung-gyu','GK',1,'FC Tokyo'),
  ('KOR','Lee Han-beom','Lee Han-beom','DEF',2,'Midtjylland'),
  ('KOR','Lee Gi-hyuk','Lee Gi-hyuk','MID',3,'Gangwon FC'),
  ('KOR','Kim Min-jae','Kim Min-jae','DEF',4,'Bayern Munich'),
  ('KOR','Kim Tae-hyeon','Kim Tae-hyeon','DEF',5,'Kashima Antlers'),
  ('KOR','Hwang In-beom','Hwang In-beom','MID',6,'Feyenoord'),
  ('KOR','Son Heung-min','Son Heung-min','FWD',7,'Los Angeles FC'),
  ('KOR','Paik Seung-ho','Paik Seung-ho','MID',8,'Birmingham City'),
  ('KOR','Cho Gue-sung','Cho Gue-sung','FWD',9,'Midtjylland'),
  ('KOR','Lee Jae-sung','Lee Jae-sung','MID',10,'Mainz 05'),
  ('KOR','Hwang Hee-chan','Hwang Hee-chan','MID',11,'Wolverhampton Wanderers'),
  ('KOR','Song Bum-keun','Song Bum-keun','GK',12,'Jeonbuk Hyundai Motors'),
  ('KOR','Lee Tae-seok','Lee Tae-seok','DEF',13,'Austria Wien'),
  ('KOR','Cho Wi-je','Cho Wi-je','DEF',14,'Jeonbuk Hyundai Motors'),
  ('KOR','Kim Moon-hwan','Kim Moon-hwan','DEF',15,'Daejeon Hana Citizen'),
  ('KOR','Park Jin-seob','Park Jin-seob','DEF',16,'Zhejiang'),
  ('KOR','Bae Jun-ho','Bae Jun-ho','MID',17,'Stoke City'),
  ('KOR','Oh Hyeon-gyu','Oh Hyeon-gyu','FWD',18,'Beşiktaş'),
  ('KOR','Lee Kang-in','Lee Kang-in','MID',19,'Paris Saint-Germain'),
  ('KOR','Yang Hyun-jun','Yang Hyun-jun','MID',20,'Celtic'),
  ('KOR','Jo Hyeon-woo','Jo Hyeon-woo','GK',21,'Ulsan HD'),
  ('KOR','Seol Young-woo','Seol Young-woo','DEF',22,'Red Star Belgrade'),
  ('KOR','Jens Castrop','Jens Castrop','DEF',23,'Borussia Mönchengladbach'),
  ('KOR','Kim Jin-gyu','Kim Jin-gyu','MID',24,'Jeonbuk Hyundai Motors'),
  ('KOR','Eom Ji-sung','Eom Ji-sung','MID',25,'Swansea City'),
  ('KOR','Lee Dong-gyeong','Lee Dong-gyeong','MID',26,'Ulsan HD'),
  ('KSA','Nawaf Al-Aqidi','Nawaf Al-Aqidi','GK',1,'Al-Nassr'),
  ('KSA','Ali Majrashi','Ali Majrashi','DEF',2,'Al-Ahli'),
  ('KSA','Ali Lajami','Ali Lajami','DEF',3,'Al-Hilal'),
  ('KSA','Abdulelah Al-Amri','Abdulelah Al-Amri','DEF',4,'Al-Nassr'),
  ('KSA','Hassan Al-Tambakti','Hassan Al-Tambakti','DEF',5,'Al-Hilal'),
  ('KSA','Nasser Al-Dawsari','Nasser Al-Dawsari','MID',6,'Al-Hilal'),
  ('KSA','Musab Al-Juwayr','Musab Al-Juwayr','MID',7,'Al-Qadsiah'),
  ('KSA','Ayman Yahya','Ayman Yahya','FWD',8,'Al-Nassr'),
  ('KSA','Firas Al-Buraikan','Firas Al-Buraikan','FWD',9,'Al-Ahli'),
  ('KSA','Salem Al-Dawsari','Salem Al-Dawsari','FWD',10,'Al-Hilal'),
  ('KSA','Saleh Al-Shehri','Saleh Al-Shehri','FWD',11,'Al-Ittihad'),
  ('KSA','Saud Abdulhamid','Saud Abdulhamid','DEF',12,'Lens'),
  ('KSA','Nawaf Boushal','Nawaf Boushal','DEF',13,'Al-Nassr'),
  ('KSA','Hassan Kadesh','Hassan Kadesh','DEF',14,'Al-Ittihad'),
  ('KSA','Abdullah Al-Khaibari','Abdullah Al-Khaibari','MID',15,'Al-Nassr'),
  ('KSA','Ziyad Al-Johani','Ziyad Al-Johani','MID',16,'Al-Ahli'),
  ('KSA','Khalid Al-Ghannam','Khalid Al-Ghannam','FWD',17,'Al-Ettifaq'),
  ('KSA','Alaa Al-Hejji','Alaa Al-Hejji','MID',18,'Neom'),
  ('KSA','Abdullah Al-Hamdan','Abdullah Al-Hamdan','FWD',19,'Al-Nassr'),
  ('KSA','Sultan Mandash','Sultan Mandash','FWD',20,'Al-Hilal'),
  ('KSA','Mohammed Al-Owais','Mohammed Al-Owais','GK',21,'Al-Ula'),
  ('KSA','Ahmed Al-Kassar','Ahmed Al-Kassar','GK',22,'Al-Qadsiah'),
  ('KSA','Mohamed Kanno','Mohamed Kanno','MID',23,'Al-Hilal'),
  ('KSA','Moteb Al-Harbi','Moteb Al-Harbi','DEF',24,'Al-Hilal'),
  ('KSA','Jehad Thakri','Jehad Thakri','DEF',25,'Al-Qadsiah'),
  ('KSA','Mohammed Abu Al-Shamat','Mohammed Abu Al-Shamat','DEF',26,'Al-Qadsiah'),
  ('MAR','Yassine Bounou','Yassine Bounou','GK',1,'Al-Hilal'),
  ('MAR','Achraf Hakimi','Achraf Hakimi','DEF',2,'Paris Saint-Germain'),
  ('MAR','Noussair Mazraoui','Noussair Mazraoui','DEF',3,'Manchester United'),
  ('MAR','Sofyan Amrabat','Sofyan Amrabat','MID',4,'Real Betis'),
  ('MAR','Nayef Aguerd','Nayef Aguerd','DEF',5,'Marseille'),
  ('MAR','Ayyoub Bouaddi','Ayyoub Bouaddi','MID',6,'Lille'),
  ('MAR','Chemsdine Talbi','Chemsdine Talbi','MID',7,'Sunderland'),
  ('MAR','Azzedine Ounahi','Azzedine Ounahi','MID',8,'Girona'),
  ('MAR','Soufiane Rahimi','Soufiane Rahimi','FWD',9,'Al Ain'),
  ('MAR','Brahim Díaz','Brahim Díaz','FWD',10,'Real Madrid'),
  ('MAR','Ismael Saibari','Ismael Saibari','MID',11,'PSV Eindhoven'),
  ('MAR','Munir Mohamedi','Munir Mohamedi','GK',12,'RS Berkane'),
  ('MAR','Zakaria El Ouahdi','Zakaria El Ouahdi','DEF',13,'Genk'),
  ('MAR','Issa Diop','Issa Diop','DEF',14,'Fulham'),
  ('MAR','Samir El Mourabet','Samir El Mourabet','MID',15,'Strasbourg'),
  ('MAR','Gessime Yassine','Gessime Yassine','MID',16,'Strasbourg'),
  ('MAR','Abde Ezzalzouli','Abde Ezzalzouli','FWD',17,'Real Betis'),
  ('MAR','Chadi Riad','Chadi Riad','DEF',18,'Crystal Palace'),
  ('MAR','Youssef Belammari','Youssef Belammari','DEF',19,'Al Ahly'),
  ('MAR','Ayoub El Kaabi','Ayoub El Kaabi','FWD',20,'Olympiacos'),
  ('MAR','Ayoube Amaimouni','Ayoube Amaimouni','FWD',21,'Eintracht Frankfurt'),
  ('MAR','Ahmed Reda Tagnaouti','Ahmed Reda Tagnaouti','GK',22,'AS FAR'),
  ('MAR','Bilal El Khannouss','Bilal El Khannouss','MID',23,'VfB Stuttgart'),
  ('MAR','Neil El Aynaoui','Neil El Aynaoui','MID',24,'Roma'),
  ('MAR','Redouane Halhal','Redouane Halhal','DEF',25,'Mechelen'),
  ('MAR','Anass Salah-Eddine','Anass Salah-Eddine','DEF',26,'PSV Eindhoven'),
  ('MEX','Raúl Rangel','Raúl Rangel','GK',1,'Guadalajara'),
  ('MEX','Jorge Sánchez','Jorge Sánchez','DEF',2,'PAOK'),
  ('MEX','César Montes','César Montes','DEF',3,'Lokomotiv Moscow'),
  ('MEX','Edson Álvarez','Edson Álvarez','DEF',4,'Fenerbahçe'),
  ('MEX','Johan Vásquez','Johan Vásquez','DEF',5,'Genoa'),
  ('MEX','Érik Lira','Érik Lira','MID',6,'Cruz Azul'),
  ('MEX','Luis Romo','Luis Romo','MID',7,'Guadalajara'),
  ('MEX','Álvaro Fidalgo','Álvaro Fidalgo','MID',8,'Real Betis'),
  ('MEX','Raúl Jiménez','Raúl Jiménez','FWD',9,'Fulham'),
  ('MEX','Alexis Vega','Alexis Vega','FWD',10,'Toluca'),
  ('MEX','Santiago Giménez','Santiago Giménez','FWD',11,'Milan'),
  ('MEX','Carlos Acevedo','Carlos Acevedo','GK',12,'Santos Laguna'),
  ('MEX','Guillermo Ochoa','Guillermo Ochoa','GK',13,'AEL Limassol'),
  ('MEX','Armando González','Armando González','FWD',14,'Guadalajara'),
  ('MEX','Israel Reyes','Israel Reyes','DEF',15,'América'),
  ('MEX','Julián Quiñones','Julián Quiñones','FWD',16,'Al-Qadsiah'),
  ('MEX','Orbelín Pineda','Orbelín Pineda','MID',17,'AEK Athens'),
  ('MEX','Obed Vargas','Obed Vargas','MID',18,'Atlético Madrid'),
  ('MEX','Gilberto Mora','Gilberto Mora','MID',19,'Tijuana'),
  ('MEX','Mateo Chávez','Mateo Chávez','DEF',20,'AZ'),
  ('MEX','César Huerta','César Huerta','FWD',21,'Anderlecht'),
  ('MEX','Guillermo Martínez','Guillermo Martínez','FWD',22,'UNAM'),
  ('MEX','Jesús Gallardo','Jesús Gallardo','DEF',23,'Toluca'),
  ('MEX','Luis Chávez','Luis Chávez','MID',24,'Dynamo Moscow'),
  ('MEX','Roberto Alvarado','Roberto Alvarado','FWD',25,'Guadalajara'),
  ('MEX','Brian Gutiérrez','Brian Gutiérrez','MID',26,'Guadalajara'),
  ('NED','Bart Verbruggen','Bart Verbruggen','GK',1,'Brighton & Hove Albion'),
  ('NED','Jurriën Timber','Jurriën Timber','DEF',2,'Arsenal'),
  ('NED','Marten de Roon','Marten de Roon','MID',3,'Atalanta'),
  ('NED','Virgil van Dijk','Virgil van Dijk','DEF',4,'Liverpool'),
  ('NED','Nathan Aké','Nathan Aké','DEF',5,'Manchester City'),
  ('NED','Jan Paul van Hecke','Jan Paul van Hecke','DEF',6,'Brighton & Hove Albion'),
  ('NED','Justin Kluivert','Justin Kluivert','MID',7,'Bournemouth'),
  ('NED','Ryan Gravenberch','Ryan Gravenberch','MID',8,'Liverpool'),
  ('NED','Wout Weghorst','Wout Weghorst','FWD',9,'Ajax'),
  ('NED','Memphis Depay','Memphis Depay','FWD',10,'Corinthians'),
  ('NED','Cody Gakpo','Cody Gakpo','FWD',11,'Liverpool'),
  ('NED','Mats Wieffer','Mats Wieffer','DEF',12,'Brighton & Hove Albion'),
  ('NED','Robin Roefs','Robin Roefs','GK',13,'Sunderland'),
  ('NED','Tijjani Reijnders','Tijjani Reijnders','MID',14,'Manchester City'),
  ('NED','Micky van de Ven','Micky van de Ven','DEF',15,'Tottenham Hotspur'),
  ('NED','Guus Til','Guus Til','MID',16,'PSV Eindhoven'),
  ('NED','Noa Lang','Noa Lang','FWD',17,'Galatasaray'),
  ('NED','Donyell Malen','Donyell Malen','FWD',18,'Roma'),
  ('NED','Brian Brobbey','Brian Brobbey','FWD',19,'Sunderland'),
  ('NED','Teun Koopmeiners','Teun Koopmeiners','MID',20,'Juventus'),
  ('NED','Frenkie de Jong','Frenkie de Jong','MID',21,'Barcelona'),
  ('NED','Denzel Dumfries','Denzel Dumfries','DEF',22,'Inter Milan'),
  ('NED','Mark Flekken','Mark Flekken','GK',23,'Bayer Leverkusen'),
  ('NED','Crysencio Summerville','Crysencio Summerville','FWD',24,'West Ham United'),
  ('NED','Jorrel Hato','Jorrel Hato','DEF',25,'Chelsea'),
  ('NED','Quinten Timber','Quinten Timber','MID',26,'Marseille'),
  ('NOR','Ørjan Nyland','Ørjan Nyland','GK',1,'Sevilla'),
  ('NOR','Morten Thorsby','Morten Thorsby','MID',2,'Cremonese'),
  ('NOR','Kristoffer Ajer','Kristoffer Ajer','DEF',3,'Brentford'),
  ('NOR','Leo Østigård','Leo Østigård','DEF',4,'Genoa'),
  ('NOR','David Møller Wolfe','David Møller Wolfe','DEF',5,'Wolverhampton Wanderers'),
  ('NOR','Patrick Berg','Patrick Berg','MID',6,'Bodø/Glimt'),
  ('NOR','Alexander Sørloth','Alexander Sørloth','FWD',7,'Atlético Madrid'),
  ('NOR','Sander Berge','Sander Berge','MID',8,'Fulham'),
  ('NOR','Erling Haaland','Erling Haaland','FWD',9,'Manchester City'),
  ('NOR','Martin Ødegaard','Martin Ødegaard','MID',10,'Arsenal'),
  ('NOR','Jørgen Strand Larsen','Jørgen Strand Larsen','FWD',11,'Crystal Palace'),
  ('NOR','Sander Tangvik','Sander Tangvik','GK',12,'Hamburger SV'),
  ('NOR','Egil Selvik','Egil Selvik','GK',13,'Watford'),
  ('NOR','Fredrik Aursnes','Fredrik Aursnes','MID',14,'Benfica'),
  ('NOR','Fredrik André Bjørkan','Fredrik André Bjørkan','DEF',15,'Bodø/Glimt'),
  ('NOR','Marcus Holmgren Pedersen','Marcus Holmgren Pedersen','DEF',16,'Torino'),
  ('NOR','Torbjørn Heggem','Torbjørn Heggem','DEF',17,'Bologna'),
  ('NOR','Kristian Thorstvedt','Kristian Thorstvedt','MID',18,'Sassuolo'),
  ('NOR','Thelo Aasgaard','Thelo Aasgaard','MID',19,'Rangers'),
  ('NOR','Antonio Nusa','Antonio Nusa','FWD',20,'RB Leipzig'),
  ('NOR','Andreas Schjelderup','Andreas Schjelderup','MID',21,'Benfica'),
  ('NOR','Oscar Bobb','Oscar Bobb','MID',22,'Fulham'),
  ('NOR','Jens Petter Hauge','Jens Petter Hauge','MID',23,'Bodø/Glimt'),
  ('NOR','Sondre Langås','Sondre Langås','DEF',24,'Derby County'),
  ('NOR','Henrik Falchener','Henrik Falchener','DEF',25,'Viking'),
  ('NOR','Julian Ryerson','Julian Ryerson','FWD',26,'Borussia Dortmund'),
  ('NZL','Max Crocombe','Max Crocombe','GK',1,'Millwall'),
  ('NZL','Tim Payne','Tim Payne','DEF',2,'Wellington Phoenix'),
  ('NZL','Francis de Vries','Francis de Vries','DEF',3,'Auckland FC'),
  ('NZL','Tyler Bindon','Tyler Bindon','DEF',4,'Sheffield United'),
  ('NZL','Michael Boxall','Michael Boxall','DEF',5,'Minnesota United FC'),
  ('NZL','Joe Bell','Joe Bell','MID',6,'Viking'),
  ('NZL','Matthew Garbett','Matthew Garbett','MID',7,'Peterborough United'),
  ('NZL','Marko Stamenić','Marko Stamenić','MID',8,'Swansea City'),
  ('NZL','Chris Wood','Chris Wood','FWD',9,'Nottingham Forest'),
  ('NZL','Sarpreet Singh','Sarpreet Singh','MID',10,'Wellington Phoenix'),
  ('NZL','Elijah Just','Elijah Just','MID',11,'Motherwell'),
  ('NZL','Alex Paulsen','Alex Paulsen','GK',12,'Lechia Gdańsk'),
  ('NZL','Liberato Cacace','Liberato Cacace','DEF',13,'Wrexham'),
  ('NZL','Alex Rufer','Alex Rufer','MID',14,'Wellington Phoenix'),
  ('NZL','Nando Pijnaker','Nando Pijnaker','DEF',15,'Auckland FC'),
  ('NZL','Finn Surman','Finn Surman','DEF',16,'Portland Timbers'),
  ('NZL','Kosta Barbarouses','Kosta Barbarouses','FWD',17,'Western Sydney Wanderers'),
  ('NZL','Ben Waine','Ben Waine','FWD',18,'Port Vale'),
  ('NZL','Ben Old','Ben Old','MID',19,'Saint-Étienne'),
  ('NZL','Callum McCowatt','Callum McCowatt','MID',20,'Silkeborg'),
  ('NZL','Jesse Randall','Jesse Randall','FWD',21,'Auckland FC'),
  ('NZL','Michael Woud','Michael Woud','GK',22,'Auckland FC'),
  ('NZL','Ryan Thomas','Ryan Thomas','MID',23,'PEC Zwolle'),
  ('NZL','Callan Elliot','Callan Elliot','DEF',24,'Auckland FC'),
  ('NZL','Lachlan Bayliss','Lachlan Bayliss','MID',25,'Newcastle Jets'),
  ('NZL','Tommy Smith','Tommy Smith','DEF',26,'Braintree Town'),
  ('PAN','Luis Mejía','Luis Mejía','GK',1,'Nacional'),
  ('PAN','César Blackman','César Blackman','DEF',2,'Slovan Bratislava'),
  ('PAN','José Córdoba','José Córdoba','DEF',3,'Norwich City'),
  ('PAN','Fidel Escobar','Fidel Escobar','DEF',4,'Saprissa'),
  ('PAN','Edgardo Fariña','Edgardo Fariña','DEF',5,'Pari Nizhny Novgorod'),
  ('PAN','Cristian Martínez','Cristian Martínez','MID',6,'Ironi Kiryat Shmona'),
  ('PAN','José Luis Rodríguez','José Luis Rodríguez','MID',7,'Juárez'),
  ('PAN','Adalberto Carrasquilla','Adalberto Carrasquilla','MID',8,'UNAM'),
  ('PAN','Tomás Rodríguez','Tomás Rodríguez','FWD',9,'Saprissa'),
  ('PAN','Ismael Díaz','Ismael Díaz','MID',10,'León'),
  ('PAN','Yoel Bárcenas','Yoel Bárcenas','MID',11,'Mazatlán'),
  ('PAN','César Samudio','César Samudio','GK',12,'Marathón'),
  ('PAN','Jiovany Ramos','Jiovany Ramos','DEF',13,'Puerto Cabello'),
  ('PAN','Carlos Harvey','Carlos Harvey','DEF',14,'Minnesota United FC'),
  ('PAN','Eric Davis','Eric Davis','DEF',15,'Plaza Amador'),
  ('PAN','Andrés Andrade','Andrés Andrade','DEF',16,'LASK'),
  ('PAN','José Fajardo','José Fajardo','FWD',17,'Universidad Católica'),
  ('PAN','Cecilio Waterman','Cecilio Waterman','FWD',18,'Universidad de Concepción'),
  ('PAN','Alberto Quintero','Alberto Quintero','MID',19,'Plaza Amador'),
  ('PAN','Aníbal Godoy','Aníbal Godoy','MID',20,'San Diego FC'),
  ('PAN','César Yanis','César Yanis','MID',21,'Cobresal'),
  ('PAN','Orlando Mosquera','Orlando Mosquera','GK',22,'Al-Fayha'),
  ('PAN','Michael Amir Murillo','Michael Amir Murillo','DEF',23,'Beşiktaş'),
  ('PAN','Azarias Londoño','Azarias Londoño','FWD',24,'Universidad Católica'),
  ('PAN','Roderick Miller','Roderick Miller','DEF',25,'Turan Tovuz'),
  ('PAN','Jorge Gutiérrez','Jorge Gutiérrez','DEF',26,'Deportivo La Guaira'),
  ('PAR','Gatito Fernández','Gatito Fernández','GK',1,'Cerro Porteño'),
  ('PAR','Gustavo Velázquez','Gustavo Velázquez','DEF',2,'Cerro Porteño'),
  ('PAR','Omar Alderete','Omar Alderete','DEF',3,'Sunderland'),
  ('PAR','Juan José Cáceres','Juan José Cáceres','DEF',4,'Dynamo Moscow'),
  ('PAR','Fabián Balbuena','Fabián Balbuena','DEF',5,'Grêmio'),
  ('PAR','Júnior Alonso','Júnior Alonso','DEF',6,'Atlético Mineiro'),
  ('PAR','Ramón Sosa','Ramón Sosa','MID',7,'Palmeiras'),
  ('PAR','Diego Gómez','Diego Gómez','MID',8,'Brighton & Hove Albion'),
  ('PAR','Antonio Sanabria','Antonio Sanabria','FWD',9,'Cremonese'),
  ('PAR','Miguel Almirón','Miguel Almirón','MID',10,'Atlanta United FC'),
  ('PAR','Maurício','Maurício','MID',11,'Palmeiras'),
  ('PAR','Orlando Gill','Orlando Gill','GK',12,'San Lorenzo'),
  ('PAR','José Canale','José Canale','DEF',13,'Lanús'),
  ('PAR','Andrés Cubas','Andrés Cubas','MID',14,'Vancouver Whitecaps FC'),
  ('PAR','Gustavo Gómez','Gustavo Gómez','DEF',15,'Palmeiras'),
  ('PAR','Damián Bobadilla','Damián Bobadilla','MID',16,'São Paulo'),
  ('PAR','Kaku','Kaku','FWD',17,'Al Ain'),
  ('PAR','Álex Arce','Álex Arce','FWD',18,'Independiente Rivadavia'),
  ('PAR','Julio Enciso','Julio Enciso','FWD',19,'Strasbourg'),
  ('PAR','Braian Ojeda','Braian Ojeda','MID',20,'Orlando City SC'),
  ('PAR','Gabriel Ávalos','Gabriel Ávalos','FWD',21,'Independiente'),
  ('PAR','Gastón Olveira','Gastón Olveira','GK',22,'Olimpia'),
  ('PAR','Matías Galarza','Matías Galarza','MID',23,'Atlanta United FC'),
  ('PAR','Gustavo Caballero','Gustavo Caballero','MID',24,'Portsmouth'),
  ('PAR','Isidro Pitta','Isidro Pitta','FWD',25,'Red Bull Bragantino'),
  ('PAR','Alexandro Maidana','Alexandro Maidana','DEF',26,'Talleres'),
  ('POR','Diogo Costa','Diogo Costa','GK',1,'Porto'),
  ('POR','Nélson Semedo','Nélson Semedo','DEF',2,'Fenerbahçe'),
  ('POR','Rúben Dias','Rúben Dias','DEF',3,'Manchester City'),
  ('POR','Tomás Araújo','Tomás Araújo','DEF',4,'Benfica'),
  ('POR','Diogo Dalot','Diogo Dalot','DEF',5,'Manchester United'),
  ('POR','Matheus Nunes','Matheus Nunes','MID',6,'Manchester City'),
  ('POR','Cristiano Ronaldo','Cristiano Ronaldo','FWD',7,'Al-Nassr'),
  ('POR','Bruno Fernandes','Bruno Fernandes','MID',8,'Manchester United'),
  ('POR','Gonçalo Ramos','Gonçalo Ramos','FWD',9,'Paris Saint-Germain'),
  ('POR','Bernardo Silva','Bernardo Silva','MID',10,'Manchester City'),
  ('POR','João Félix','João Félix','FWD',11,'Al-Nassr'),
  ('POR','José Sá','José Sá','GK',12,'Wolverhampton Wanderers'),
  ('POR','Renato Veiga','Renato Veiga','DEF',13,'Villarreal'),
  ('POR','Gonçalo Inácio','Gonçalo Inácio','DEF',14,'Sporting CP'),
  ('POR','João Neves','João Neves','MID',15,'Paris Saint-Germain'),
  ('POR','Francisco Trincão','Francisco Trincão','FWD',16,'Sporting CP'),
  ('POR','Rafael Leão','Rafael Leão','FWD',17,'Milan'),
  ('POR','Pedro Neto','Pedro Neto','FWD',18,'Chelsea'),
  ('POR','Gonçalo Guedes','Gonçalo Guedes','FWD',19,'Real Sociedad'),
  ('POR','João Cancelo','João Cancelo','DEF',20,'Barcelona'),
  ('POR','Rúben Neves','Rúben Neves','MID',21,'Al-Hilal'),
  ('POR','Rui Silva','Rui Silva','GK',22,'Sporting CP'),
  ('POR','Vitinha','Vitinha','MID',23,'Paris Saint-Germain'),
  ('POR','Samú Costa','Samú Costa','DEF',24,'Mallorca'),
  ('POR','Nuno Mendes','Nuno Mendes','DEF',25,'Paris Saint-Germain'),
  ('POR','Francisco Conceição','Francisco Conceição','FWD',26,'Juventus'),
  ('QAT','Mahmud Abunada','Mahmud Abunada','GK',1,'Al-Rayyan'),
  ('QAT','Pedro Miguel','Pedro Miguel','DEF',2,'Al-Sadd'),
  ('QAT','Lucas Mendes','Lucas Mendes','DEF',3,'Al-Wakrah'),
  ('QAT','Issa Laye','Issa Laye','DEF',4,'Al-Arabi'),
  ('QAT','Jassem Gaber','Jassem Gaber','DEF',5,'Al-Rayyan'),
  ('QAT','Abdulaziz Hatem','Abdulaziz Hatem','MID',6,'Al-Rayyan'),
  ('QAT','Ahmed Alaaeldin','Ahmed Alaaeldin','FWD',7,'Al-Rayyan'),
  ('QAT','Edmilson Junior','Edmilson Junior','FWD',8,'Al-Duhail'),
  ('QAT','Mohammed Muntari','Mohammed Muntari','FWD',9,'Al-Gharafa'),
  ('QAT','Hassan Al-Haydos','Hassan Al-Haydos','FWD',10,'Al-Sadd'),
  ('QAT','Akram Afif','Akram Afif','FWD',11,'Al-Sadd'),
  ('QAT','Karim Boudiaf','Karim Boudiaf','MID',12,'Al-Duhail'),
  ('QAT','Ayoub Al-Oui','Ayoub Al-Oui','DEF',13,'Al-Gharafa'),
  ('QAT','Homam Ahmed','Homam Ahmed','DEF',14,'Cultural Leonesa'),
  ('QAT','Yusuf Abdurisag','Yusuf Abdurisag','FWD',15,'Al-Wakrah'),
  ('QAT','Boualem Khoukhi','Boualem Khoukhi','DEF',16,'Al-Sadd'),
  ('QAT','Ahmed Al-Ganehi','Ahmed Al-Ganehi','MID',17,'Al-Gharafa'),
  ('QAT','Sultan Al-Brake','Sultan Al-Brake','DEF',18,'Al-Duhail'),
  ('QAT','Almoez Ali','Almoez Ali','FWD',19,'Al-Duhail'),
  ('QAT','Ahmed Fathy','Ahmed Fathy','MID',20,'Al-Arabi'),
  ('QAT','Salah Zakaria','Salah Zakaria','GK',21,'Al-Duhail'),
  ('QAT','Meshaal Barsham','Meshaal Barsham','GK',22,'Al-Sadd'),
  ('QAT','Assim Madibo','Assim Madibo','MID',23,'Al-Wakrah'),
  ('QAT','Tahsin Jamshid','Tahsin Jamshid','FWD',24,'Al-Duhail'),
  ('QAT','Al-Hashmi Al-Hussain','Al-Hashmi Al-Hussain','DEF',25,'Al-Arabi'),
  ('QAT','Mohamed Manai','Mohamed Manai','FWD',26,'Al-Shamal'),
  ('RSA','Ronwen Williams','Ronwen Williams','GK',1,'Mamelodi Sundowns'),
  ('RSA','Thabang Matuludi','Thabang Matuludi','DEF',2,'Polokwane City'),
  ('RSA','Khulumani Ndamane','Khulumani Ndamane','DEF',3,'Mamelodi Sundowns'),
  ('RSA','Teboho Mokoena','Teboho Mokoena','MID',4,'Mamelodi Sundowns'),
  ('RSA','Thalente Mbatha','Thalente Mbatha','MID',5,'Orlando Pirates'),
  ('RSA','Aubrey Modiba','Aubrey Modiba','DEF',6,'Mamelodi Sundowns'),
  ('RSA','Oswin Appollis','Oswin Appollis','FWD',7,'Orlando Pirates'),
  ('RSA','Tshepang Moremi','Tshepang Moremi','FWD',8,'Orlando Pirates'),
  ('RSA','Lyle Foster','Lyle Foster','FWD',9,'Burnley'),
  ('RSA','Relebohile Mofokeng','Relebohile Mofokeng','FWD',10,'Orlando Pirates'),
  ('RSA','Themba Zwane','Themba Zwane','MID',11,'Mamelodi Sundowns'),
  ('RSA','Thapelo Maseko','Thapelo Maseko','FWD',12,'AEL Limassol'),
  ('RSA','Sphephelo Sithole','Sphephelo Sithole','MID',13,'Tondela'),
  ('RSA','Mbekezeli Mbokazi','Mbekezeli Mbokazi','DEF',14,'Chicago Fire FC'),
  ('RSA','Iqraam Rayners','Iqraam Rayners','FWD',15,'Mamelodi Sundowns'),
  ('RSA','Sipho Chaine','Sipho Chaine','GK',16,'Orlando Pirates'),
  ('RSA','Evidence Makgopa','Evidence Makgopa','FWD',17,'Orlando Pirates'),
  ('RSA','Samukele Kabini','Samukele Kabini','DEF',18,'Molde'),
  ('RSA','Nkosinathi Sibisi','Nkosinathi Sibisi','DEF',19,'Orlando Pirates'),
  ('RSA','Khuliso Mudau','Khuliso Mudau','DEF',20,'Mamelodi Sundowns'),
  ('RSA','Ime Okon','Ime Okon','DEF',21,'Hannover 96'),
  ('RSA','Ricardo Goss','Ricardo Goss','GK',22,'Siwelele'),
  ('RSA','Jayden Adams','Jayden Adams','MID',23,'Mamelodi Sundowns'),
  ('RSA','Olwethu Makhanya','Olwethu Makhanya','DEF',24,'Philadelphia Union'),
  ('RSA','Kamogelo Sebelebele','Kamogelo Sebelebele','FWD',25,'Orlando Pirates'),
  ('RSA','Bradley Cross','Bradley Cross','DEF',26,'Kaizer Chiefs'),
  ('SCO','Angus Gunn','Angus Gunn','GK',1,'Nottingham Forest'),
  ('SCO','Aaron Hickey','Aaron Hickey','DEF',2,'Brentford'),
  ('SCO','Andy Robertson','Andy Robertson','DEF',3,'Liverpool'),
  ('SCO','Scott McTominay','Scott McTominay','MID',4,'Napoli'),
  ('SCO','Grant Hanley','Grant Hanley','DEF',5,'Hibernian'),
  ('SCO','Kieran Tierney','Kieran Tierney','DEF',6,'Celtic'),
  ('SCO','John McGinn','John McGinn','MID',7,'Aston Villa'),
  ('SCO','Tyler Fletcher','Tyler Fletcher','MID',8,'Manchester United'),
  ('SCO','Lyndon Dykes','Lyndon Dykes','FWD',9,'Charlton Athletic'),
  ('SCO','Ché Adams','Ché Adams','FWD',10,'Torino'),
  ('SCO','Ryan Christie','Ryan Christie','MID',11,'Bournemouth'),
  ('SCO','Liam Kelly','Liam Kelly','GK',12,'Rangers'),
  ('SCO','Jack Hendry','Jack Hendry','DEF',13,'Al-Ettifaq'),
  ('SCO','Ross Stewart','Ross Stewart','FWD',14,'Southampton'),
  ('SCO','John Souttar','John Souttar','DEF',15,'Rangers'),
  ('SCO','Dominic Hyam','Dominic Hyam','DEF',16,'Wrexham'),
  ('SCO','Ben Gannon-Doak','Ben Gannon-Doak','FWD',17,'Bournemouth'),
  ('SCO','George Hirst','George Hirst','FWD',18,'Ipswich Town'),
  ('SCO','Lewis Ferguson','Lewis Ferguson','MID',19,'Bologna'),
  ('SCO','Lawrence Shankland','Lawrence Shankland','FWD',20,'Heart of Midlothian'),
  ('SCO','Craig Gordon','Craig Gordon','GK',21,'Heart of Midlothian'),
  ('SCO','Nathan Patterson','Nathan Patterson','DEF',22,'Everton'),
  ('SCO','Kenny McLean','Kenny McLean','MID',23,'Norwich City'),
  ('SCO','Anthony Ralston','Anthony Ralston','DEF',24,'Celtic'),
  ('SCO','Findlay Curtis','Findlay Curtis','FWD',25,'Kilmarnock'),
  ('SCO','Scott McKenna','Scott McKenna','DEF',26,'Dinamo Zagreb'),
  ('SEN','Yehvann Diouf','Yehvann Diouf','GK',1,'Nice'),
  ('SEN','Mamadou Sarr','Mamadou Sarr','DEF',2,'Chelsea'),
  ('SEN','Kalidou Koulibaly','Kalidou Koulibaly','DEF',3,'Al-Hilal'),
  ('SEN','Abdoulaye Seck','Abdoulaye Seck','DEF',4,'Maccabi Haifa'),
  ('SEN','Idrissa Gueye','Idrissa Gueye','MID',5,'Everton'),
  ('SEN','Pathé Ciss','Pathé Ciss','MID',6,'Rayo Vallecano'),
  ('SEN','Assane Diao','Assane Diao','FWD',7,'Como'),
  ('SEN','Lamine Camara','Lamine Camara','MID',8,'Monaco'),
  ('SEN','Bamba Dieng','Bamba Dieng','FWD',9,'Lorient'),
  ('SEN','Sadio Mané','Sadio Mané','FWD',10,'Al-Nassr'),
  ('SEN','Nicolas Jackson','Nicolas Jackson','FWD',11,'Bayern Munich'),
  ('SEN','Cherif Ndiaye','Cherif Ndiaye','FWD',12,'Samsunspor'),
  ('SEN','Iliman Ndiaye','Iliman Ndiaye','FWD',13,'Everton'),
  ('SEN','Ismail Jakobs','Ismail Jakobs','DEF',14,'Galatasaray'),
  ('SEN','Krépin Diatta','Krépin Diatta','DEF',15,'Monaco'),
  ('SEN','Édouard Mendy','Édouard Mendy','GK',16,'Al-Ahli'),
  ('SEN','Pape Matar Sarr','Pape Matar Sarr','MID',17,'Tottenham Hotspur'),
  ('SEN','Ismaïla Sarr','Ismaïla Sarr','FWD',18,'Crystal Palace'),
  ('SEN','Moussa Niakhaté','Moussa Niakhaté','DEF',19,'Lyon'),
  ('SEN','Ibrahim Mbaye','Ibrahim Mbaye','FWD',20,'Paris Saint-Germain'),
  ('SEN','Habib Diarra','Habib Diarra','MID',21,'Sunderland'),
  ('SEN','Bara Sapoko Ndiaye','Bara Sapoko Ndiaye','MID',22,'Bayern Munich'),
  ('SEN','Mory Diaw','Mory Diaw','GK',23,'Le Havre'),
  ('SEN','Antoine Mendy','Antoine Mendy','DEF',24,'Nice'),
  ('SEN','El Hadji Malick Diouf','El Hadji Malick Diouf','DEF',25,'West Ham United'),
  ('SEN','Pape Gueye','Pape Gueye','MID',26,'Villarreal'),
  ('SUI','Gregor Kobel','Gregor Kobel','GK',1,'Borussia Dortmund'),
  ('SUI','Miro Muheim','Miro Muheim','DEF',2,'Hamburger SV'),
  ('SUI','Silvan Widmer','Silvan Widmer','DEF',3,'Mainz 05'),
  ('SUI','Nico Elvedi','Nico Elvedi','DEF',4,'Borussia Mönchengladbach'),
  ('SUI','Manuel Akanji','Manuel Akanji','DEF',5,'Inter Milan'),
  ('SUI','Denis Zakaria','Denis Zakaria','MID',6,'Monaco'),
  ('SUI','Breel Embolo','Breel Embolo','FWD',7,'Rennes'),
  ('SUI','Remo Freuler','Remo Freuler','MID',8,'Bologna'),
  ('SUI','Johan Manzambi','Johan Manzambi','MID',9,'SC Freiburg'),
  ('SUI','Granit Xhaka','Granit Xhaka','MID',10,'Sunderland'),
  ('SUI','Dan Ndoye','Dan Ndoye','FWD',11,'Nottingham Forest'),
  ('SUI','Yvon Mvogo','Yvon Mvogo','GK',12,'Lorient'),
  ('SUI','Ricardo Rodriguez','Ricardo Rodriguez','DEF',13,'Real Betis'),
  ('SUI','Ardon Jashari','Ardon Jashari','MID',14,'Milan'),
  ('SUI','Djibril Sow','Djibril Sow','MID',15,'Sevilla'),
  ('SUI','Christian Fassnacht','Christian Fassnacht','FWD',16,'Young Boys'),
  ('SUI','Rubén Vargas','Rubén Vargas','FWD',17,'Sevilla'),
  ('SUI','Eray Cömert','Eray Cömert','DEF',18,'Valencia'),
  ('SUI','Noah Okafor','Noah Okafor','FWD',19,'Leeds United'),
  ('SUI','Michel Aebischer','Michel Aebischer','MID',20,'Pisa'),
  ('SUI','Marvin Keller','Marvin Keller','GK',21,'Young Boys'),
  ('SUI','Fabian Rieder','Fabian Rieder','MID',22,'FC Augsburg'),
  ('SUI','Zeki Amdouni','Zeki Amdouni','FWD',23,'Burnley'),
  ('SUI','Aurèle Amenda','Aurèle Amenda','DEF',24,'Eintracht Frankfurt'),
  ('SUI','Luca Jaquez','Luca Jaquez','DEF',25,'VfB Stuttgart'),
  ('SUI','Cedric Itten','Cedric Itten','FWD',26,'Fortuna Düsseldorf'),
  ('SWE','Jacob Widell Zetterström','Jacob Widell Zetterström','GK',1,'Derby County'),
  ('SWE','Gustaf Lagerbielke','Gustaf Lagerbielke','DEF',2,'Braga'),
  ('SWE','Victor Lindelöf','Victor Lindelöf','DEF',3,'Aston Villa'),
  ('SWE','Isak Hien','Isak Hien','DEF',4,'Atalanta'),
  ('SWE','Gabriel Gudmundsson','Gabriel Gudmundsson','DEF',5,'Leeds United'),
  ('SWE','Herman Johansson','Herman Johansson','DEF',6,'FC Dallas'),
  ('SWE','Lucas Bergvall','Lucas Bergvall','MID',7,'Tottenham Hotspur'),
  ('SWE','Daniel Svensson','Daniel Svensson','DEF',8,'Borussia Dortmund'),
  ('SWE','Alexander Isak','Alexander Isak','FWD',9,'Liverpool'),
  ('SWE','Benjamin Nygren','Benjamin Nygren','MID',10,'Celtic'),
  ('SWE','Anthony Elanga','Anthony Elanga','FWD',11,'Newcastle United'),
  ('SWE','Viktor Johansson','Viktor Johansson','GK',12,'Stoke City'),
  ('SWE','Ken Sema','Ken Sema','MID',13,'Pafos'),
  ('SWE','Hjalmar Ekdal','Hjalmar Ekdal','DEF',14,'Burnley'),
  ('SWE','Carl Starfelt','Carl Starfelt','DEF',15,'Celta Vigo'),
  ('SWE','Jesper Karlström','Jesper Karlström','MID',16,'Udinese'),
  ('SWE','Viktor Gyökeres','Viktor Gyökeres','FWD',17,'Arsenal'),
  ('SWE','Yasin Ayari','Yasin Ayari','MID',18,'Brighton & Hove Albion'),
  ('SWE','Mattias Svanberg','Mattias Svanberg','MID',19,'VfL Wolfsburg'),
  ('SWE','Eric Smith','Eric Smith','DEF',20,'FC St. Pauli'),
  ('SWE','Alexander Bernhardsson','Alexander Bernhardsson','DEF',21,'Holstein Kiel'),
  ('SWE','Besfort Zeneli','Besfort Zeneli','MID',22,'Union Saint-Gilloise'),
  ('SWE','Kristoffer Nordfeldt','Kristoffer Nordfeldt','GK',23,'AIK'),
  ('SWE','Elliot Stroud','Elliot Stroud','DEF',24,'Mjällby AIF'),
  ('SWE','Gustaf Nilsson','Gustaf Nilsson','FWD',25,'Club Brugge'),
  ('SWE','Taha Ali','Taha Ali','FWD',26,'Malmö FF'),
  ('TUN','Mouhib Chamakh','Mouhib Chamakh','GK',1,'Club Africain'),
  ('TUN','Ali Abdi','Ali Abdi','DEF',2,'Nice'),
  ('TUN','Montassar Talbi','Montassar Talbi','DEF',3,'Lorient'),
  ('TUN','Omar Rekik','Omar Rekik','DEF',4,'Maribor'),
  ('TUN','Adem Arous','Adem Arous','DEF',5,'Kasımpaşa'),
  ('TUN','Dylan Bronn','Dylan Bronn','DEF',6,'Servette'),
  ('TUN','Elias Achouri','Elias Achouri','FWD',7,'Copenhagen'),
  ('TUN','Elias Saad','Elias Saad','FWD',8,'Hannover 96'),
  ('TUN','Hazem Mastouri','Hazem Mastouri','FWD',9,'Dynamo Makhachkala'),
  ('TUN','Hannibal Mejbri','Hannibal Mejbri','MID',10,'Burnley'),
  ('TUN','Ismaël Gharbi','Ismaël Gharbi','MID',11,'FC Augsburg'),
  ('TUN','Mortadha Ben Ouanes','Mortadha Ben Ouanes','DEF',12,'Kasımpaşa'),
  ('TUN','Rani Khedira','Rani Khedira','MID',13,'Union Berlin'),
  ('TUN','Khalil Ayari','Khalil Ayari','MID',14,'Paris Saint-Germain'),
  ('TUN','Hadj Mahmoud','Hadj Mahmoud','MID',15,'Lugano'),
  ('TUN','Aymen Dahmen','Aymen Dahmen','GK',16,'CS Sfaxien'),
  ('TUN','Ellyes Skhiri','Ellyes Skhiri','MID',17,'Eintracht Frankfurt'),
  ('TUN','Rayan Elloumi','Rayan Elloumi','FWD',18,'Vancouver Whitecaps FC'),
  ('TUN','Firas Chaouat','Firas Chaouat','FWD',19,'Club Africain'),
  ('TUN','Yan Valery','Yan Valery','DEF',20,'Young Boys'),
  ('TUN','Mohamed Amine Ben Hamida','Mohamed Amine Ben Hamida','DEF',21,'Espérance de Tunis'),
  ('TUN','Sabri Ben Hessen','Sabri Ben Hessen','GK',22,'Étoile du Sahel'),
  ('TUN','Moutaz Neffati','Moutaz Neffati','DEF',23,'IFK Norrköping'),
  ('TUN','Raed Chikhaoui','Raed Chikhaoui','DEF',24,'US Monastir'),
  ('TUN','Anis Ben Slimane','Anis Ben Slimane','MID',25,'Norwich City'),
  ('TUN','Sebastian Tounekti','Sebastian Tounekti','MID',26,'Celtic'),
  ('TUR','Mert Günok','Mert Günok','GK',1,'Fenerbahçe'),
  ('TUR','Zeki Çelik','Zeki Çelik','DEF',2,'Roma'),
  ('TUR','Merih Demiral','Merih Demiral','DEF',3,'Al-Ahli'),
  ('TUR','Çağlar Söyüncü','Çağlar Söyüncü','DEF',4,'Fenerbahçe'),
  ('TUR','Salih Özcan','Salih Özcan','MID',5,'Borussia Dortmund'),
  ('TUR','Orkun Kökçü','Orkun Kökçü','MID',6,'Beşiktaş'),
  ('TUR','Kerem Aktürkoğlu','Kerem Aktürkoğlu','FWD',7,'Fenerbahçe'),
  ('TUR','Arda Güler','Arda Güler','FWD',8,'Real Madrid'),
  ('TUR','Deniz Gül','Deniz Gül','FWD',9,'Porto'),
  ('TUR','Hakan Çalhanoğlu','Hakan Çalhanoğlu','MID',10,'Inter Milan'),
  ('TUR','Kenan Yıldız','Kenan Yıldız','FWD',11,'Juventus'),
  ('TUR','Altay Bayındır','Altay Bayındır','GK',12,'Manchester United'),
  ('TUR','Eren Elmalı','Eren Elmalı','DEF',13,'Galatasaray'),
  ('TUR','Abdülkerim Bardakcı','Abdülkerim Bardakcı','DEF',14,'Galatasaray'),
  ('TUR','Ozan Kabak','Ozan Kabak','DEF',15,'TSG Hoffenheim'),
  ('TUR','İsmail Yüksek','İsmail Yüksek','MID',16,'Fenerbahçe'),
  ('TUR','İrfan Can Kahveci','İrfan Can Kahveci','FWD',17,'Kasımpaşa'),
  ('TUR','Mert Müldür','Mert Müldür','DEF',18,'Fenerbahçe'),
  ('TUR','Yunus Akgün','Yunus Akgün','FWD',19,'Galatasaray'),
  ('TUR','Ferdi Kadıoğlu','Ferdi Kadıoğlu','DEF',20,'Brighton & Hove Albion'),
  ('TUR','Barış Alper Yılmaz','Barış Alper Yılmaz','FWD',21,'Galatasaray'),
  ('TUR','Kaan Ayhan','Kaan Ayhan','MID',22,'Galatasaray'),
  ('TUR','Uğurcan Çakır','Uğurcan Çakır','GK',23,'Galatasaray'),
  ('TUR','Oğuz Aydın','Oğuz Aydın','FWD',24,'Fenerbahçe'),
  ('TUR','Samet Akaydin','Samet Akaydin','DEF',25,'Çaykur Rizespor'),
  ('TUR','Can Uzun','Can Uzun','FWD',26,'Eintracht Frankfurt'),
  ('URU','Sergio Rochet','Sergio Rochet','GK',1,'Internacional'),
  ('URU','José María Giménez','José María Giménez','DEF',2,'Atlético Madrid'),
  ('URU','Sebastián Cáceres','Sebastián Cáceres','DEF',3,'América'),
  ('URU','Ronald Araújo','Ronald Araújo','DEF',4,'Barcelona'),
  ('URU','Manuel Ugarte','Manuel Ugarte','MID',5,'Manchester United'),
  ('URU','Rodrigo Bentancur','Rodrigo Bentancur','MID',6,'Tottenham Hotspur'),
  ('URU','Nicolás de la Cruz','Nicolás de la Cruz','MID',7,'Flamengo'),
  ('URU','Federico Valverde','Federico Valverde','MID',8,'Real Madrid'),
  ('URU','Darwin Núñez','Darwin Núñez','FWD',9,'Al-Hilal'),
  ('URU','Giorgian de Arrascaeta','Giorgian de Arrascaeta','MID',10,'Flamengo'),
  ('URU','Facundo Pellistri','Facundo Pellistri','FWD',11,'Panathinaikos'),
  ('URU','Santiago Mele','Santiago Mele','GK',12,'Monterrey'),
  ('URU','Guillermo Varela','Guillermo Varela','DEF',13,'Flamengo'),
  ('URU','Agustín Canobbio','Agustín Canobbio','MID',14,'Fluminense'),
  ('URU','Emiliano Martínez','Emiliano Martínez','MID',15,'Palmeiras'),
  ('URU','Mathías Olivera','Mathías Olivera','DEF',16,'Napoli'),
  ('URU','Matías Viña','Matías Viña','DEF',17,'River Plate'),
  ('URU','Brian Rodríguez','Brian Rodríguez','FWD',18,'América'),
  ('URU','Rodrigo Aguirre','Rodrigo Aguirre','FWD',19,'UANL'),
  ('URU','Maximiliano Araújo','Maximiliano Araújo','MID',20,'Sporting CP'),
  ('URU','Federico Viñas','Federico Viñas','FWD',21,'Oviedo'),
  ('URU','Joaquín Piquerez','Joaquín Piquerez','MID',22,'Palmeiras'),
  ('URU','Fernando Muslera','Fernando Muslera','GK',23,'Estudiantes'),
  ('URU','Santiago Bueno','Santiago Bueno','DEF',24,'Wolverhampton Wanderers'),
  ('URU','Juan Manuel Sanabria','Juan Manuel Sanabria','MID',25,'Real Salt Lake'),
  ('URU','Rodrigo Zalazar','Rodrigo Zalazar','MID',26,'Braga'),
  ('USA','Matt Turner','Matt Turner','GK',1,'New England Revolution'),
  ('USA','Sergiño Dest','Sergiño Dest','DEF',2,'PSV Eindhoven'),
  ('USA','Chris Richards','Chris Richards','DEF',3,'Crystal Palace'),
  ('USA','Tyler Adams','Tyler Adams','MID',4,'Bournemouth'),
  ('USA','Antonee Robinson','Antonee Robinson','DEF',5,'Fulham'),
  ('USA','Auston Trusty','Auston Trusty','DEF',6,'Celtic'),
  ('USA','Giovanni Reyna','Giovanni Reyna','MID',7,'Borussia Mönchengladbach'),
  ('USA','Weston McKennie','Weston McKennie','MID',8,'Juventus'),
  ('USA','Ricardo Pepi','Ricardo Pepi','FWD',9,'PSV Eindhoven'),
  ('USA','Christian Pulisic','Christian Pulisic','FWD',10,'Milan'),
  ('USA','Brenden Aaronson','Brenden Aaronson','FWD',11,'Leeds United'),
  ('USA','Miles Robinson','Miles Robinson','DEF',12,'FC Cincinnati'),
  ('USA','Tim Ream','Tim Ream','DEF',13,'Charlotte FC'),
  ('USA','Sebastian Berhalter','Sebastian Berhalter','MID',14,'Vancouver Whitecaps FC'),
  ('USA','Cristian Roldan','Cristian Roldan','MID',15,'Seattle Sounders FC'),
  ('USA','Alex Freeman','Alex Freeman','DEF',16,'Villarreal'),
  ('USA','Malik Tillman','Malik Tillman','MID',17,'Bayer Leverkusen'),
  ('USA','Maximilian Arfsten','Maximilian Arfsten','DEF',18,'Columbus Crew'),
  ('USA','Haji Wright','Haji Wright','FWD',19,'Coventry City'),
  ('USA','Folarin Balogun','Folarin Balogun','FWD',20,'Monaco'),
  ('USA','Timothy Weah','Timothy Weah','FWD',21,'Marseille'),
  ('USA','Mark McKenzie','Mark McKenzie','DEF',22,'Toulouse'),
  ('USA','Joe Scally','Joe Scally','DEF',23,'Borussia Mönchengladbach'),
  ('USA','Matt Freese','Matt Freese','GK',24,'New York City FC'),
  ('USA','Chris Brady','Chris Brady','GK',25,'Chicago Fire FC'),
  ('USA','Alejandro Zendejas','Alejandro Zendejas','FWD',26,'América'),
  ('UZB','Utkir Yusupov','Utkir Yusupov','GK',1,'Navbahor Namangan'),
  ('UZB','Abdukodir Khusanov','Abdukodir Khusanov','DEF',2,'Manchester City'),
  ('UZB','Khojiakbar Alijonov','Khojiakbar Alijonov','DEF',3,'Pakhtakor'),
  ('UZB','Farrukh Sayfiev','Farrukh Sayfiev','DEF',4,'Neftchi Fergana'),
  ('UZB','Rustam Ashurmatov','Rustam Ashurmatov','DEF',5,'Esteghlal'),
  ('UZB','Akmal Mozgovoy','Akmal Mozgovoy','MID',6,'Pakhtakor'),
  ('UZB','Otabek Shukurov','Otabek Shukurov','MID',7,'Baniyas'),
  ('UZB','Jamshid Iskanderov','Jamshid Iskanderov','MID',8,'Neftchi Fergana'),
  ('UZB','Odiljon Hamrobekov','Odiljon Hamrobekov','MID',9,'Tractor'),
  ('UZB','Jaloliddin Masharipov','Jaloliddin Masharipov','MID',10,'Esteghlal'),
  ('UZB','Oston Urunov','Oston Urunov','MID',11,'Persepolis'),
  ('UZB','Abduvohid Nematov','Abduvohid Nematov','GK',12,'Nasaf'),
  ('UZB','Sherzod Nasrullaev','Sherzod Nasrullaev','DEF',13,'Nasaf'),
  ('UZB','Eldor Shomurodov','Eldor Shomurodov','FWD',14,'İstanbul Başakşehir'),
  ('UZB','Umar Eshmurodov','Umar Eshmurodov','DEF',15,'Nasaf'),
  ('UZB','Botirali Ergashev','Botirali Ergashev','GK',16,'Neftchi Fergana'),
  ('UZB','Dostonbek Khamdamov','Dostonbek Khamdamov','MID',17,'Pakhtakor'),
  ('UZB','Abdulla Abdullaev','Abdulla Abdullaev','DEF',18,'Dibba'),
  ('UZB','Azizjon Ganiev','Azizjon Ganiev','MID',19,'Al Bataeh'),
  ('UZB','Azizbek Amonov','Azizbek Amonov','FWD',20,'Dinamo Samarqand'),
  ('UZB','Igor Sergeev','Igor Sergeev','FWD',21,'Persepolis'),
  ('UZB','Abbosbek Fayzullaev','Abbosbek Fayzullaev','MID',22,'İstanbul Başakşehir'),
  ('UZB','Sherzod Esanov','Sherzod Esanov','MID',23,'Bukhara'),
  ('UZB','Bekhruz Karimov','Bekhruz Karimov','DEF',24,'Surkhon Termiz'),
  ('UZB','Avazbek Ulmasaliev','Avazbek Ulmasaliev','DEF',25,'AGMK'),
  ('UZB','Jakhongir Urozov','Jakhongir Urozov','DEF',26,'Dinamo Samarqand');

-- 1) Upsert : crée/actualise chaque joueur de la liste définitive, le (ré)active.
insert into ref.players (team_id, name, display_name, position, shirt_number, club, active)
select t.id, s.name, s.display_name, s.position, s.shirt_number, s.club, true
from _wc_squads s
join ref.teams t on t.fifa_code = s.fifa_code
on conflict (team_id, lower(name)) do update set
  display_name = excluded.display_name,
  position     = excluded.position,
  shirt_number = excluded.shirt_number,
  club         = excluded.club,
  active       = true,
  updated_at   = now();

-- 2) Désactive les joueurs des équipes importées absents de la liste définitive (sans suppression).
update ref.players p
set active = false, updated_at = now()
from ref.teams t
where p.team_id = t.id
  and t.fifa_code in (select distinct fifa_code from _wc_squads)
  and p.active
  and not exists (
    select 1 from _wc_squads s
    where s.fifa_code = t.fifa_code
      and lower(s.name) = lower(p.name)
  );

drop table _wc_squads;
